### ISSUE TITLE
TerrainGridAlphaMapTest throws NPE when spacebar is pressed

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1116]
In `master` branch at a8f5ac0:
```
Jun 09, 2019 8:59:02 AM com.jme3.terrain.noise.filter.PerturbFilter filter
INFO: Found origSize : 147 and offset: 17 for workSize : 181 and magnitude : 0.119
Jun 09, 2019 8:59:03 AM com.jme3.terrain.noise.filter.PerturbFilter filter
INFO: Found origSize : 147 and offset: 17 for workSize : 181 and magnitude : 0.119
fixed normals (0.0, 0.0, 0.0)
Jun 09, 2019 8:59:19 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.NullPointerException
	at jme3test.terrain.TerrainGridAlphaMapTest$3.onAction(TerrainGridAlphaMapTest.java:297)
	at com.jme3.input.InputManager.invokeActions(InputManager.java:171)
	at com.jme3.input.InputManager.onKeyEventQueued(InputManager.java:471)
	at com.jme3.input.InputManager.processQueue(InputManager.java:864)
	at com.jme3.input.InputManager.update(InputManager.java:916)
	at com.jme3.app.LegacyApplication.update(LegacyApplication.java:724)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:244)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:197)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by stephengold** [comment]
Fixed in `master` branch at 5586c28c9554c34108dad63aa308bc8fe1ff8a2b .
