### ISSUE TITLE
AssetLoad Exception thrown by TestTangentGenBadModels

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1142]
Running on Linux:
```
Jul 12, 2019 9:19:30 AM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.2.3-v3.2-6660
 * Branch: v3.2
 * Git Hash: a8bf087
 * Build Date: 2019-07-12
Jul 12, 2019 9:19:30 AM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: null
 * Driver Version: null
 * Scaling Factor: 1
Jul 12, 2019 9:19:30 AM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
 * Vendor: NVIDIA Corporation
 * Renderer: GeForce GT 545/PCIe/SSE2
 * OpenGL Version: 4.6.0 NVIDIA 390.116
 * GLSL Version: 4.60 NVIDIA
 * Profile: Compatibility
Jul 12, 2019 9:19:31 AM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.LinuxEnvironmentPlugin
Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event0): Failed to open device /dev/input/event0 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event1): Failed to open device /dev/input/event1 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event10): Failed to open device /dev/input/event10 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event11): Failed to open device /dev/input/event11 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event12): Failed to open device /dev/input/event12 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event13): Failed to open device /dev/input/event13 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event14): Failed to open device /dev/input/event14 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event15): Failed to open device /dev/input/event15 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event2): Failed to open device /dev/input/event2 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event3): Failed to open device /dev/input/event3 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event4): Failed to open device /dev/input/event4 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event5): Failed to open device /dev/input/event5 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event6): Failed to open device /dev/input/event6 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event7): Failed to open device /dev/input/event7 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event8): Failed to open device /dev/input/event8 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event9): Failed to open device /dev/input/event9 (13)


Jul 12, 2019 9:19:31 AM net.java.games.input.ControllerEnvironment log
INFO: Linux plugin claims to have found 0 controllers

Jul 12, 2019 9:19:31 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio Renderer Information
 * Device: OpenAL Soft
 * Vendor: OpenAL Community
 * Renderer: OpenAL Soft
 * Version: 1.1 ALSOFT 1.15.1
 * Supported channels: 64
 * ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
 * AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
Jul 12, 2019 9:19:31 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
Jul 12, 2019 9:19:31 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio effect extension version: 1.0
Jul 12, 2019 9:19:31 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio max auxiliary sends: 4
Jul 12, 2019 9:19:31 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Loading animations that will be later applied to scene features.
Jul 12, 2019 9:19:31 AM com.jme3.scene.plugins.blender.textures.TextureHelper readTextureData
INFO: Loading model's textures.
Jul 12, 2019 9:19:31 AM com.jme3.scene.plugins.blender.meshes.TemporalMesh triangulate
WARNING: There were problems with triangulating the faces of a mesh: MyModel
	Unable to find two closest vertices while triangulating face.
Jul 12, 2019 9:19:31 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.asset.AssetLoadException: An exception has occurred while loading asset: Models/TangentBugs/test.blend
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:261)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:420)
	at jme3test.light.TestTangentGenBadModels.simpleInitApp(TestTangentGenBadModels.java:40)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Unexpected importer exception occurred: null
	at com.jme3.scene.plugins.blender.BlenderLoader.load(BlenderLoader.java:223)
	at com.jme3.scene.plugins.blender.BlenderLoader.load(BlenderLoader.java:88)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	... 8 more
Caused by: java.lang.NullPointerException
	at com.jme3.scene.plugins.blender.textures.blending.TextureBlenderAWT.blend(TextureBlenderAWT.java:146)
	at com.jme3.scene.plugins.blender.textures.CombinedTexture.blend(CombinedTexture.java:363)
	at com.jme3.scene.plugins.blender.textures.CombinedTexture.flatten(CombinedTexture.java:172)
	at com.jme3.scene.plugins.blender.materials.MaterialContext.applyMaterial(MaterialContext.java:182)
	at com.jme3.scene.plugins.blender.meshes.TemporalMesh.prepareFacesGeometry(TemporalMesh.java:621)
	at com.jme3.scene.plugins.blender.meshes.TemporalMesh.toGeometries(TemporalMesh.java:483)
	at com.jme3.scene.plugins.blender.objects.ObjectHelper.toObject(ObjectHelper.java:248)
	at com.jme3.scene.plugins.blender.BlenderLoader.load(BlenderLoader.java:105)
	... 10 more

```

**Comment by stephengold** [comment]
Running on Windows:
```
Jul 12, 2019 11:31:52 AM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.2.3-v3.2-6660
 * Branch: v3.2
 * Git Hash: a8bf087
 * Build Date: 2019-07-12
Jul 12, 2019 11:31:52 AM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: nvd3dumx,nvwgf2umx,nvwgf2umx
 * Driver Version: 23.21.13.8873
 * Scaling Factor: 1
Jul 12, 2019 11:31:52 AM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
 * Vendor: NVIDIA Corporation
 * Renderer: GeForce GT 545/PCIe/SSE2
 * OpenGL Version: 4.6.0 NVIDIA 388.73
 * GLSL Version: 4.60 NVIDIA
 * Profile: Compatibility
Jul 12, 2019 11:31:53 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio Renderer Information
 * Device: OpenAL Soft
 * Vendor: OpenAL Community
 * Renderer: OpenAL Soft
 * Version: 1.1 ALSOFT 1.15.1
 * Supported channels: 64
 * ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
 * AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
Jul 12, 2019 11:31:53 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
Jul 12, 2019 11:31:53 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio effect extension version: 1.0
Jul 12, 2019 11:31:53 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio max auxiliary sends: 4
Jul 12, 2019 11:31:53 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Loading animations that will be later applied to scene features.
Jul 12, 2019 11:31:53 AM com.jme3.scene.plugins.blender.textures.TextureHelper readTextureData
INFO: Loading model's textures.
Jul 12, 2019 11:31:53 AM com.jme3.scene.plugins.blender.meshes.TemporalMesh triangulate
WARNING: There were problems with triangulating the faces of a mesh: MyModel
	Unable to find two closest vertices while triangulating face.
Jul 12, 2019 11:31:54 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.asset.AssetLoadException: An exception has occurred while loading asset: Models/TangentBugs/test.blend
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:261)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:420)
	at jme3test.light.TestTangentGenBadModels.simpleInitApp(TestTangentGenBadModels.java:40)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Unexpected importer exception occurred: null
	at com.jme3.scene.plugins.blender.BlenderLoader.load(BlenderLoader.java:223)
	at com.jme3.scene.plugins.blender.BlenderLoader.load(BlenderLoader.java:88)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	... 8 more
Caused by: java.lang.NullPointerException
	at com.jme3.scene.plugins.blender.textures.blending.TextureBlenderAWT.blend(TextureBlenderAWT.java:146)
	at com.jme3.scene.plugins.blender.textures.CombinedTexture.blend(CombinedTexture.java:363)
	at com.jme3.scene.plugins.blender.textures.CombinedTexture.flatten(CombinedTexture.java:172)
	at com.jme3.scene.plugins.blender.materials.MaterialContext.applyMaterial(MaterialContext.java:182)
	at com.jme3.scene.plugins.blender.meshes.TemporalMesh.prepareFacesGeometry(TemporalMesh.java:621)
	at com.jme3.scene.plugins.blender.meshes.TemporalMesh.toGeometries(TemporalMesh.java:483)
	at com.jme3.scene.plugins.blender.objects.ObjectHelper.toObject(ObjectHelper.java:248)
	at com.jme3.scene.plugins.blender.BlenderLoader.load(BlenderLoader.java:105)
	... 10 more
```

**Comment by typically** [comment]
This bug still exists; it is traceable to line 146 of `TextureBlenderAWT.java`:

`ColorSpace colorSpace = baseImage.getColorSpace() != null ? baseImage.getColorSpace() : ColorSpace.Linear;`

The variable `baseImage` can be `null` at this point. The following will fix the bug:

`ColorSpace colorSpace = (baseImage != null && baseImage.getColorSpace() != null) ? baseImage.getColorSpace() : ColorSpace.Linear;`

**Comment by stephengold** [comment]
Since TestTangentGenBadModels and TextureBlenderAWT were removed from the Engine on 19 April 2020, this issue is now moot.
