### ISSUE TITLE
ConnectException thrown by TestChatClient

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1143]
Running 3.2.3-v3.2-6660 on Linux:
```
Setting logging to max
Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.jme3.network.kernel.tcp.SocketConnector.<init>(SocketConnector.java:65)
	at com.jme3.network.Network.connectToServer(Network.java:165)
	at jme3test.network.TestChatClient.<init>(TestChatClient.java:94)
	at jme3test.network.TestChatClient.main(TestChatClient.java:155)
Chat client is terminating.

```

**Comment by stephengold** [comment]
Okay, there probably wasn't a server running at the time. The chat client need to handle that situation more gracefully.

**Comment by pspeed42** [comment]
But it's telling you exactly what happened.  The connection was refused because there was no host.
I'm not sure how much hand-holding we want to do in simple tests like this.
