### ISSUE TITLE
TestResizableApp crashes with LWJGL3 on Windows

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1191]
This test has been broken since JME 3.1 at least:
```
Sep 20, 2019 10:14:16 AM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.1-stable
 * Branch: HEAD
 * Git Hash: af04bf9
 * Build Date: 2017-02-13
Sep 20, 2019 10:14:17 AM com.jme3.app.LegacyApplication handleError
SEVERE: Failed to create display
java.lang.NullPointerException
	at jme3test.app.TestResizableApp.reshape(TestResizableApp.java:63)
	at com.jme3.system.lwjgl.LwjglWindow$2.invoke(LwjglWindow.java:207)
	at org.lwjgl.glfw.GLFWWindowSizeCallback.callback(GLFWWindowSizeCallback.java:45)
	at org.lwjgl.system.JNI.invokePV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwShowWindow(GLFW.java:1692)
	at com.jme3.system.lwjgl.LwjglWindow.createContext(LwjglWindow.java:246)
	at com.jme3.system.lwjgl.LwjglWindow.initInThread(LwjglWindow.java:324)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:443)
	at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:295)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:463)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:424)
	at com.jme3.app.SimpleApplication.start(SimpleApplication.java:125)
	at jme3test.app.TestResizableApp.main(TestResizableApp.java:56)

Sep 20, 2019 10:14:17 AM com.jme3.system.lwjgl.LwjglWindow run
SEVERE: Display initialization failed. Cannot continue.
```

and it's still broken in current master branch:
```
Sep 20, 2019 10:21:29 AM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.3-6918
 * Branch: master
 * Git Hash: 46a52af
 * Build Date: 2019-09-20
Sep 20, 2019 10:21:31 AM com.jme3.app.LegacyApplication handleError
SEVERE: Failed to create display
java.lang.NullPointerException
	at jme3test.app.TestResizableApp.reshape(TestResizableApp.java:63)
	at com.jme3.system.lwjgl.LwjglWindow$2.invoke(LwjglWindow.java:258)
	at org.lwjgl.glfw.GLFWWindowSizeCallbackI.callback(GLFWWindowSizeCallbackI.java:35)
	at org.lwjgl.system.JNI.invokePV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwShowWindow(GLFW.java:2477)
	at com.jme3.system.lwjgl.LwjglWindow.showWindow(LwjglWindow.java:301)
	at com.jme3.system.lwjgl.LwjglWindow.createContext(LwjglWindow.java:295)
	at com.jme3.system.lwjgl.LwjglWindow.initInThread(LwjglWindow.java:453)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:578)
	at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:427)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:463)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:424)
	at com.jme3.app.SimpleApplication.start(SimpleApplication.java:125)
	at jme3test.app.TestResizableApp.main(TestResizableApp.java:56)

Sep 20, 2019 10:21:31 AM com.jme3.system.lwjgl.LwjglWindow run
SEVERE: Display initialization failed. Cannot continue.
```

**Comment by stephengold** [comment]
The test works fine with LWJGL2 on Windows.

**Comment by stephengold** [comment]
The test works fine for me on Linux, both with LWJGL2 and LWJGL3. So perhaps a Windows-specific issue.

**Comment by tonihele** [comment]
Might also be, the problem is that the resize event triggers before the application is initialized.

**Comment by Sailsman63** [comment]
Anybody have data on which versions of windows/what video card/etc trigger this?

I ask because another project I work on had some issues that were first reported around November related to a driver bug...

Also: Best way to force use of the lwjgl3 library from the command line? (just the engine gradle build)

**Comment by stephengold** [comment]
It would've been Windows 7 with a GeForce GT 545 video card.

**Comment by stephengold** [comment]
I don't know any way to force lwjgl3 from the command line. AFAIK apps are configured for either LWJGL 2.x or LWJGL 3.x at build time.

The best way to configure jme3-examples is to edit its build.gradle file:
```
//    compile project(':jme3-lwjgl')
    compile project(':jme3-lwjgl3')
```

**Comment by stephengold** [comment]
I recreated the issue on Windows7 using master SHAID=0252c1b, then tested master SHAID=59793d4 to confirm that the issue was resolved.
