### ISSUE TITLE
NPE in SafeArrayList on AppState detach and remve of raw listener

### ISSUE THREAD

**Issue by devent** [jMonkeyEngine/jmonkeyengine#1212]
Hello. I just got an NPE in the SafeArrayList while detaching application states. The state is removing a raw listener on detach. This is happening some time, not always. My understanding is that the SafeArrayList where the raw listeners are stored should be "safe".

Here is the removed app state:

```
    @Override
    public void stateDetached(AppStateManager stateManager) {
        L.debug("detached");
        inputManager.removeRawInputListener(this);
        super.stateDetached(stateManager);
    }
```

Here are the logs:

```
	[DEBUG] 2019-11-11 16:15:46,581 [JavaFX Application Thread] MouseCursorState - detached
	[DEBUG] 2019-11-11 16:15:46,584 [JavaFX Application Thread] MouseMoveMapState - detached
	[DEBUG] 2019-11-11 16:15:46,585 [JavaFX Application Thread] MoveViewCoordinatesStateBase - detached
	Nov. 11, 2019 4:15:46 NACHM. com.jme3.app.LegacyApplication handleError
	SEVERE: Uncaught exception thrown in Thread[main,5,main]
	java.lang.NullPointerException
		at com.jme3.input.InputManager.processQueue(InputManager.java:825)
		at com.jme3.input.InputManager.update(InputManager.java:914)
		at com.jme3.app.LegacyApplication.update(LegacyApplication.java:724)
		at com.jme3.app.SimpleApplication.update(SimpleApplication.java:227)
		at com.jme3.system.lwjgl.LwjglWindow.runLoop(LwjglWindow.java:499)
		at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:581)
		at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:423)
		at com.jme3.app.LegacyApplication.start(LegacyApplication.java:463)
		at com.jme3.app.LegacyApplication.start(LegacyApplication.java:424)
		at com.jme3.app.SimpleApplication.start(SimpleApplication.java:125)
		at com.jme3.app.SimpleApplication$start.callCurrent(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:160)
		at com.anrisoftware.dwarfhustle.game.jme.mainmap.internal.app.AbstractGameApplication.start(AbstractGameApplication.groovy:128)
		at com.anrisoftware.dwarfhustle.game.jme.mainmap.internal.app.AbstractGameApplication$start.call(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
		at com.anrisoftware.dwarfhustle.game.jme.mainmap.internal.app.AbstractGameApplication.startApp(AbstractGameApplication.groovy:69)
```

It looks to me like a bug, that is why I'm posting it here and not in the forum. Maybe I'm using the app state wrong?

I just see that the detach code is called on a different thread. But I assumed that the SafeArrayList is thread safe. It is not thread safe? If SafeArrayList is suppose to be thread safe then this is definitely a bug.

**Comment by pspeed42** [comment]
stateAttached() and stateDetached() are mostly used for debugging.  They are called from whatever thread that the app state was attached/detached on which may not by the same thread that is running the app state or the input manager.  In almost no cases is it safe to call JME classes from these methods.

SafeArrayList is not thread safe.  My guess is that you are detaching your app state from a separate thread.

Probably what you really want to do is remove your listener on cleanup().

**Comment by devent** [comment]
Ok thank you. Maybe add the information that SafeArrayList is not thread safe in the Javadoc? Because the name implies it and the current documentation is ambiguous at best. I will close the issue.

**Comment by pspeed42** [comment]
It's literally in the first sentence of the javadoc that no one reads: https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/java/com/jme3/util/SafeArrayList.java#L37

...and then later expands upon that.
