### ISSUE TITLE
BlenderLoader 2.8 Support

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#1217]
This issue can be seen as a Milestone for improving the Blender Loader to support Blender 2.8.

In the meantime, I strongly suggest improving the way importing fails:
https://github.com/jMonkeyEngine/sdk/issues/209
```
Caused by: java.io.IOException: Unknown data type: int64_t
	at com.jme3.scene.plugins.blender.BlenderLoader.load(BlenderLoader.java:221)
	at com.jme3.scene.plugins.blender.BlenderLoader.load(BlenderLoader.java:88)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	... 121 more
Caused by: com.jme3.scene.plugins.blender.file.BlenderFileException: Unknown data type: int64_t
	at com.jme3.scene.plugins.blender.file.Structure$DataType.getDataType(Structure.java:318)
	at com.jme3.scene.plugins.blender.file.Field.fill(Field.java:92)
	at com.jme3.scene.plugins.blender.file.Structure.fill(Structure.java:118)
	at com.jme3.scene.plugins.blender.file.Field.fill(Field.java:183)
	at com.jme3.scene.plugins.blender.file.Structure.fill(Structure.java:118)
	at com.jme3.scene.plugins.blender.file.Pointer.fetchData(Pointer.java:122)
	at com.jme3.scene.plugins.blender.objects.ObjectHelper.toObject(ObjectHelper.java:170)
	at com.jme3.scene.plugins.blender.BlenderLoader.load(BlenderLoader.java:105)
	... 123 more
```

If there is a version field, BlenderLoader should ensure that the Version is < 2.8. Otherwise there could the UnsupportedOperationException be thrown with a meaningful String ("Only Blender files up to 2.8 are supported. Use GTLF or other File Exchange Formats for later blender versions").

Also if someone is curious, go ahead and see how much you can fix there. Implementing an `int64_t` data structure certainly is no problem, but the question will be what other challenges are down the road.

See here https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-blender/src/main/java/com/jme3/scene/plugins/blender/file/Structure.java#L293 it would be a single line addition to pass that at least

**Comment by stephengold** [comment]
Since jme3-blender was removed from the Engine on 19 April 2020, this issue is now moot.

**Comment by Jezorko** [comment]
@stephengold I have just downloaded the JMonkey SDK ([release 3.3](https://github.com/jMonkeyEngine/sdk/releases)) and it still attempts to use this plugin to load `.blender` files, so the issue is still valid.

It should probably be removed from the SDK (and an error shown that file is not supported).

**Comment by stephengold** [comment]
Thanks for getting in touch. I agree that the feature should be removed from the SDK, and I'm sure it will be---assuming there's ever an SDK release for JME 3.4 or later.

FYI, there's a separate issue tracker for the SDK: https://github.com/jMonkeyEngine/sdk/issues
