### ISSUE TITLE
Common/MatDefs/Light/PBRLighting.vert exception in 3.3.0-beta1(after switch from alpha5)

### ISSUE THREAD

**Issue by oxplay2** [jMonkeyEngine/jmonkeyengine#1236]
Hi, after switch to new beta1 of 3.3 seems like im getting new issue. i dont think its related to my changes, because i dont trully made any to that Test.

Im using shape keys to manipulate morph shapes of Character models. So its related probably only for morph shapes models.

```
gru 22, 2019 3:08:39 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[main,5,main]
com.jme3.renderer.RendererException: compile error in: ShaderSource[name=Common/MatDefs/Light/PBRLighting.vert, defines, type=Vertex, language=GLSL150]
0(423) : error C1111: non-lvalue actual parameter #2 cannot be out parameter ("norm.27")

	at com.jme3.renderer.opengl.GLRenderer.updateShaderSourceData(GLRenderer.java:1476)
	at com.jme3.renderer.opengl.GLRenderer.updateShaderData(GLRenderer.java:1503)
	at com.jme3.renderer.opengl.GLRenderer.setShader(GLRenderer.java:1567)
	at com.jme3.material.logic.SinglePassAndImageBasedLightingLogic.render(SinglePassAndImageBasedLightingLogic.java:259)
	at com.jme3.material.Technique.render(Technique.java:166)
	at com.jme3.material.Material.render(Material.java:1026)
	at com.jme3.renderer.RenderManager.renderGeometry(RenderManager.java:614)
	at com.jme3.renderer.queue.RenderQueue.renderGeometryList(RenderQueue.java:266)
	at com.jme3.renderer.queue.RenderQueue.renderQueue(RenderQueue.java:305)
	at com.jme3.renderer.RenderManager.renderViewPortQueues(RenderManager.java:877)
	at com.jme3.renderer.RenderManager.flushQueue(RenderManager.java:779)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1108)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:272)
	at com.jme3.system.lwjgl.LwjglWindow.runLoop(LwjglWindow.java:503)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:585)
	at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:427)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:463)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:424)
	at com.jme3.app.SimpleApplication.start(SimpleApplication.java:127)
```

This refer to:

```
421	    void Morph_Compute(inout vec4 pos){
422	        #if (NUM_TARGETS_BUFFERS == 2)
423	            Morph_Compute_Pos_Norm(pos,vec3(0.0));
424	            return;
425	        #elif (NUM_TARGETS_BUFFERS == 3)
426	            Morph_Compute_Pos_Norm_Tan(pos, vec3(0.0), vec3(0.0));
427	            return;
428	        #endif
429	        Morph_Compute_Pos(pos);
430	    }
431	
```
below line is problematic:

`423	            Morph_Compute_Pos_Norm(pos,vec3(0.0));`

**Comment by oxplay2** [comment]
seems like related to:

https://github.com/jMonkeyEngine/jmonkeyengine/commit/30df2f1b87f38529c0958776b57c8ba9d68d2992

**Comment by riccardobl** [comment]
mhh... the error says it
`non-lvalue actual parameter #2 cannot be out parameter ("norm.27")`
-->
` void Morph_Compute_Pos_Norm(inout vec4 pos, inout vec3 norm)`

When you removed the dummy variables you must have broken it in some implementations that make those vec3 constant.

**Comment by oxplay2** [comment]
"When you removed" - i dont, its beta1 code.

seems like from his fix(https://github.com/jMonkeyEngine/jmonkeyengine/commit/30df2f1b87f38529c0958776b57c8ba9d68d2992), it should contain just:

`if (gl2 != null && !(gl instanceof GLES_30)) {`

and

`float sum = 0.0;`

without removing summy variables then?

**Comment by riccardobl** [comment]
Oh yes, sorry, i mean @joliver82 , not you.
The change regarding these two lines
```
vec3 dummy_norm = vec3(0.0);
vec3 dummy_tan = vec3(0.0);
```
in the commit you linked, should be revered.
Then it should work fine.

**Comment by Ali-RS** [comment]
I guess there was an issue with those dummy vectors on Android that @joliver82 removed them.  See https://github.com/jMonkeyEngine/jmonkeyengine/issues/635#issuecomment-555311881

**Comment by riccardobl** [comment]
Mh, ok. But they don't need to be global.

**Comment by riccardobl** [comment]
Try this patch https://github.com/riccardobl/jmonkeyengine/commit/817f4b355272690e27b7bc05a54cc88bb710a258

I didn't test it, but it should be ok.

**Comment by Ali-RS** [comment]
Tried your patch, working fine for me.

**Comment by oxplay2** [comment]
thanks Riccardo and Ali :)

**Comment by Ali-RS** [comment]
@riccardobl  what about declaring them as global constant with the "const" qualifier?

```
  const vec3 dummy_norm = vec3(0.0);
  const vec3 dummy_tan = vec3(0.0);
```

**Comment by Ali-RS** [comment]
@riccardobl  any chance for a PR?

**Comment by joliver82** [comment]
Sorry for breaking this, I missed the inout in those parameters :man_facepalming: but it worked properly in both my mobile and in my desktop. Thanks @riccardobl for addressing it ;)

**Comment by riccardobl** [comment]
Don't worry. It seems a compiler specific issue, it happens. Should be fixed in master.

**Comment by Ali-RS** [comment]
Thanks.

**Comment by oxplay2** [comment]
thanks
