### ISSUE TITLE
RenderException in loadExtensions

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#1243]
Loading Extensions doesn't seem to work on GL3+ (at least in core profile, as the compat profile bypasses this problem).

Note that for this to work you need AppSetttings#set("GraphicsDebug", true). Then:
```
com.jme3.renderer.RendererException: An OpenGL error occurred - Invalid enum argument (Error Code: 1280)
    at com.jme3.renderer.opengl.GLDebug.checkError(GLDebug.java:46)
    at com.jme3.renderer.opengl.GLDebugES.glGetString(GLDebugES.java:287)
    at com.jme3.renderer.opengl.GLRenderer.loadExtensions(GLRenderer.java:145)
    at com.jme3.renderer.opengl.GLRenderer.loadCapabilitiesCommon(GLRenderer.java:294)
    at com.jme3.renderer.opengl.GLRenderer.loadCapabilities(GLRenderer.java:583)
    at com.jme3.renderer.opengl.GLRenderer.initialize(GLRenderer.java:599)
    at com.jme3.system.lwjgl.LwjglContext.initContextFirstTime(LwjglContext.java:284)
    at com.jme3.system.lwjgl.LwjglContext.internalCreate(LwjglContext.java:424)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:117)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
    at java.lang.Thread.run(Thread.java:748)
```

https://github.com/jMonkeyEngine/jmonkeyengine/blob/3f59008566a45aa04437c87c21e99233b0692407/jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java#L578-L582

This is the problem:
We need a much better way to differentiate the OpenGL Version, because https://github.com/jMonkeyEngine/jmonkeyengine/blob/3f59008566a45aa04437c87c21e99233b0692407/jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java#L135-L145 relies on that.

I am not 100% sure, that Caps.OpenGL30 is not set because of that, but according to the stack trace it really seems to me, that here, openGL ES is falsely detected and thus OpenGL30 is not present. This means we use the OpenGL 1 way of querying for extensions, which doesn't work in the Core Profile.

I think this issue has a much greater impact on everything, as every code trying to detect OpenGL30 or any version for that matter, would have failed before(?) when in core profile.

**Comment by MeFisto94** [comment]
Debugging more into this:
```
caps = {JumboEnumSet@2628}  size = 12
 0 = {Caps@2636} "GLSL100"
 1 = {Caps@2637} "GeometryShader"
 2 = {Caps@2638} "TesselationShader"
 3 = {Caps@2639} "MeshInstancing"
 4 = {Caps@2640} "Multisample"
 5 = {Caps@2641} "OpenGLES20"
 6 = {Caps@2642} "OpenGLES30"
 7 = {Caps@2643} "GLSL300"
 8 = {Caps@2644} "OpenGLES31"
 9 = {Caps@2645} "GLSL310"
 10 = {Caps@2646} "OpenGLES32"
 11 = {Caps@2647} "GLSL320"
```

So probably we're after GLSL300? Aren't the GLSL Versions in sync starting with GL3.0?
Is "OpenGL 3.0" a Cap after all? I don't think so, as loadCapabilitiesGL2 looks like this:
```
int oglVer = extractVersion(gl.glGetString(GL.GL_VERSION));

        if (oglVer >= 200) {
            caps.add(Caps.OpenGL20);
            if (oglVer >= 210) {
                caps.add(Caps.OpenGL21);
            }
            if (oglVer >= 300) {
                caps.add(Caps.OpenGL30);
            }
```

I don't question that code, but I note here that the official way is probably to see what GLSL is available here, especially since the above code will add the OpenGL 2.0 cap, even though we might be on 4.5 core profile, where all of those methods are deprecated already. What are your thoughts on this specifically?

For now I'll just fix the above statement with loadCapabilitiesGL2.

**Comment by MeFisto94** [comment]
Me and @riccardobl have investigated this and the issues reported in #1256:
`public class GLDebugDesktop extends GLDebugES implements GL2, GL3, GL4 {`
`public class GLDebugES extends GLDebug implements GL, GL2, GLES_30, GLFbo, GLExt {`

So when using GraphicsDebug gl is instanceof GLES_30 and thus tries to load in ES mode.
The easy solution is splitting GLDebugDesktop from GLDebugES, however maybe we can improve the situation in general.

**Comment by MeFisto94** [comment]
Closing as being a duplicate of #1272
