### ISSUE TITLE
Problem with multisample postprocessing

### ISSUE THREAD

**Issue by noncom** [jMonkeyEngine/jmonkeyengine#1246]
This ticket is the result of the discussion in Discord and its conclusions.

There appears to be an inconsistence within JME postprocessing stack, related to multisampling, that, according to my preliminary findings, encompasses such problems as:
1. Some of the stock shaders are not built to support multisampling (for example, FXAA), thus when multisampling is enabled, these shaders fail.
2. The failure looks like replacing the screenbuffer texture with some randrom texture from the loaded ones, thus effectively breaking the rendering pipeline.
3. There's no warning or error that notifies the user that a particular shader is not compatible with multisampling and cannot be used.
4. There's no documentation notice about what shaders allow that usage or not.
5. Unaware contributors make shaders that are incompatible with multisampling. That could have been avoided if the contribution guide included the relevant section for shaders on how to make them multisampling-compatible.
6. The problem can be silently "eliminated" by preceeding the line of post effects of the affected `FilterPostProcessor` with one of the shaders that was by chance made compatible with multisampling. That is not a real solution, however, it's currently widely adopted among the community on a level of a belief that a lucky sequence of postprocessing effects will work and the user just needs to find it by randomly changing the order of the filters in the postprocessing stack until it works.

**Reproducing the problem:**

The simplest reproduction of the problem can be made by creating a `FilterPostProcessor` within any JME project (for example, TestPBRLighting or a barest project with a box and a sky sphere and some textures), setting the number of samples on application settings to, for example, 4, setting the number of samples on the `FilterPostProcessor` to the same amount, and assigning two filters to it:
1. `FXAAFilter`
2. `ToneMapFilter`

which will lead to the viewport screenbuffer to be replaced with the texture of the environment map:

![image](https://user-images.githubusercontent.com/2920144/72114823-d9f26680-3355-11ea-973f-49a5105e8111.png)

while the reverse combination of the filters will seemingly work:

![image](https://user-images.githubusercontent.com/2920144/72114838-e8d91900-3355-11ea-93fc-07bcb906c9e7.png)

The issue is also reproduced and confirmed by Oxplay on his machine.

The statement of this issue implies that preceeding the `FilterPostProcessor` chain of effects with even a passthrough filter that simply does nothing except for treating the possibility of multisampling correctly, fixes the symptom is confirmed.

This project https://github.com/noncom/jme-multisampling-stopgap contains such a proof 
 of a passthrough filter that can be used at the start of the chain with any number of following filters that don't support multisampling and eliminate the glitch.

Take note that that filter also requires
```glsl
 #extension GL_ARB_texture_multisample : enable
```
which in turn requires specifying `GLSL150` version requirement in its `j3md`.

However, such an "approach" is not a solution, since the problem clearly lies within the JME pipeline or `FilterPostProcessor` pipeline.

As of now I did not yet get into how the pipelines work inside so I don't know why exactly this "approach" fixes the texture glitch. My current guess is that such a filter simply converges the multiple texture samples into one, thus providing a `sampler2D` as its output, that is later nonchalantly used by the following filters. If this is true, then the following filters are already silently receiving the color data collapsed to a single sample and might not always be desirable? This must be a problem?

I am not sure how this could have been missed until now, but this looks like a huge gap in the solidity of documentation and/or rendreing/postprocessing stacks and requires some attention.

**Comment by stephengold** [comment]
Thanks for reporting the issue and providing such thorough analysis!

**Comment by stephengold** [comment]
* I reproduced the issue by modifying `TestPBRLighting` in `master` branch as you suggested.
* I pushed a change to `TestPBRLighting` to set the number of samples based on the rendering context, which should make it slightly easier for others to reproduce the issue. (They still must use the setting dialog and uncomment the FXAA filter.)
* I confirmed that disabling MSAA *or* swapping the order (of the FXAA and ToneMap filters) *or* inserting a MultiSamplingFix (before the FXAA) works around the issue.

I'm not very familiar with how filters work. Perhaps the solution is to require that all filters support MSAA? Or to recognize which ones don't and coddle them appropriately.

**Comment by noncom** [comment]
Yeah, so, we thought about the approaches that you are describing, but I am not so qualified to actually know what to do here, and it's going to be a while before I really get to this. So I think that actually it also would be great if @riccardobl a look into this too since he most probably has some clear understanding of how can this be handled, but not in a way to just simply cancel the issue, rather to use it as an opportunity to maybe improve the post processing stack.

 Why not, there were a lot of talks about that so maybe it is worth to start thinking about this.

**Comment by jayfella** [comment]
From what I know based on the conversation on discord:

If multisampling is enabled, the screen texture is passed to the multisampling texture:

```
uniform sampler2DMS m_Texture;
```

and at this stage, the unsampled texture is NULL.
```
uniform sampler2D m_Texture;
```

Therefore  **until** a filter reads the sampled texture, the unsampled texture is always null.

If multisampling is enabled and **no** filter reads the multisampled texture, the FPP will return a null texture - which will result in the first texture that was loaded being displayed (usually the BitmapFont texture).

The problem can be *patched* by putting a Filter at the front (zero index) of the list that simply reads from the multisampled texture and outputs it straight back - i.e. a passthrough filter.

**Comment by stephengold** [comment]
Perhaps there's no reason for `FXAAFilter` to support multisampling. But I notice that `CrossHatchFilter` exhibits the same issue (screen buffer replaced by environment map texture). So it seems like it's not merely an FXAA issue.

And `DepthOfFieldFilter` fails to compile if it's the front filter in an MSAA environment:
```
Jan 11, 2020 2:27:27 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.renderer.RendererException: compile error in: ShaderSource[name=Common/MatDefs/Post/DepthOfField.frag, defines, type=Fragment, language=GLSL150]
0(188) : error C1115: unable to find compatible overloaded function "texture(sampler2DMS, vec2)"
0(189) : error C1115: unable to find compatible overloaded function "texture(sampler2DMS, vec2)"
0(190) : error C1115: unable to find compatible overloaded function "texture(sampler2DMS, vec2)"
0(191) : error C1115: unable to find compatible overloaded function "texture(sampler2DMS, vec2)"
0(192) : error C1115: unable to find compatible overloaded function "texture(sampler2DMS, vec2)"
0(193) : error C1115: unable to find compatible overloaded function "texture(sampler2DMS, vec2)"
0(194) : error C1115: unable to find compatible overloaded function "texture(sampler2DMS, vec2)"
0(195) : error C1115: unable to find compatible overloaded function "texture(sampler2DMS, vec2)"
0(196) : error C1115: unable to find compatible overloaded function "texture(sampler2DMS, vec2)"
0(197) : error C1115: unable to find compatible overloaded function "texture(sampler2DMS, vec2)"
0(198) : error C1115: unable to find compatible overloaded function "texture(sampler2DMS, vec2)"
0(199) : error C1115: unable to find compatible overloaded function "texture(sampler2DMS, vec2)"

	at com.jme3.renderer.opengl.GLRenderer.updateShaderSourceData(GLRenderer.java:1476)
	at com.jme3.renderer.opengl.GLRenderer.updateShaderData(GLRenderer.java:1503)
	at com.jme3.renderer.opengl.GLRenderer.setShader(GLRenderer.java:1567)
	at com.jme3.material.logic.DefaultTechniqueDefLogic.render(DefaultTechniqueDefLogic.java:94)
	at com.jme3.material.Technique.render(Technique.java:166)
	at com.jme3.material.Material.render(Material.java:1026)
	at com.jme3.renderer.RenderManager.renderGeometry(RenderManager.java:614)
	at com.jme3.post.FilterPostProcessor.renderProcessing(FilterPostProcessor.java:230)
	at com.jme3.post.FilterPostProcessor.renderFilterChain(FilterPostProcessor.java:314)
	at com.jme3.post.FilterPostProcessor.postFrame(FilterPostProcessor.java:334)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1114)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:272)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:197)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:748)
```
(Prepending a `MultiSamplingFix` filter addresses the compile error in `DepthOfField.frag`, so I'm convinced that the compile error is a different symptom of this same issue.)
