### ISSUE TITLE
IllegalStateException from software skinning with zero weights per vertex

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1309]
@oxplay2 reported the following crash in `SkinningControl` (new animation system):
```
mar 14, 2020 9:56:14 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[main,5,main]
java.lang.IllegalStateException: Max weights per vert is incorrectly set!
at com.jme3.anim.SkinningControl.applySkinning(SkinningControl.java:464)
at com.jme3.anim.SkinningControl.softwareSkinUpdate(SkinningControl.java:446)
at com.jme3.anim.SkinningControl.controlRenderSoftware(SkinningControl.java:263)
at com.jme3.anim.SkinningControl.controlRender(SkinningControl.java:303)
at com.jme3.scene.control.AbstractControl.render(AbstractControl.java:118)
```

I'm guessing `mesh.getMaxNumWeights()` returned 0. He says the same scene renders fine with hardware skinning. Perhaps `SkinningControl` should simply skip over meshes without weights.

**Comment by stephengold** [comment]
Another possibility is that `mesh` had bone weights but `mesh.maxNumWeights` wasn't set correctly.

**Comment by Scrappers-glitch** [comment]
Any progress on this issue so far?

**Comment by stephengold** [comment]
@Scrappers-glitch not that I'm aware of. Note that the issue isn't assigned to anyone.
