### ISSUE TITLE
TestUseAfterFree causes AssertionError in deleteNativeObject()

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1353]
I encountered this while testing the JME 3.3.1 release candidate (commit= a150deb ) in SDK 3.2.4 on Linux Mint.

To reproduce:
1. run the `TestUseAfterFree` app in jme3-examples
2. wait for the "Assiging [sic] texture to deleted object!" message on the console
3. press Esc key (to close the app)

Symptoms:
 + the app does not close
 + the mouse pointer disappears
 + a stack trace is generated to the console, for an assertion error in `NativeObjectManager.deleteNativeObject()` at line 127 invoked from `NativeObjectManager.deleteAllObjects()` at line 204 invoked from `GLRenderer.cleanup()` at line 649

I don't have the complete stack trace because I couldn't copy/paste without using the mouse. To recover use of my computer, I used Ctrl+Alt+Del to log out and log back in again.

**Comment by stephengold** [comment]
JME 3.3.0-stable has the exact same issue, except that the line number in `GLRenderer.cleanup()` is 640 instead of 649.

To avoid disabling the mouse pointer, I added `flyCam.setDragToRotate(true);` and obtained the following stack trace:
```text
Apr 20, 2020 3:06:27 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio max auxiliary sends: 4
Assiging texture to deleted object!
Apr 20, 2020 3:06:39 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.AssertionError
	at com.jme3.util.NativeObjectManager.deleteNativeObject(NativeObjectManager.java:127)
	at com.jme3.util.NativeObjectManager.deleteAllObjects(NativeObjectManager.java:204)
	at com.jme3.renderer.opengl.GLRenderer.cleanup(GLRenderer.java:640)
	at com.jme3.system.lwjgl.LwjglDisplay.destroyContext(LwjglDisplay.java:160)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.deinitInThread(LwjglAbstractDisplay.java:196)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:237)
	at java.lang.Thread.run(Thread.java:748)


Exception: java.lang.AssertionError thrown from the UncaughtExceptionHandler in thread "jME3 Main"
```

**Comment by stephengold** [comment]
JME 3.2.4-stable had essentially the same issue:
```text
Apr 20, 2020 3:19:51 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio max auxiliary sends: 4
Assiging texture to deleted object!
Apr 20, 2020 3:20:02 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.AssertionError
	at com.jme3.util.NativeObjectManager.deleteNativeObject(NativeObjectManager.java:127)
	at com.jme3.util.NativeObjectManager.deleteAllObjects(NativeObjectManager.java:204)
	at com.jme3.renderer.opengl.GLRenderer.cleanup(GLRenderer.java:585)
	at com.jme3.system.lwjgl.LwjglDisplay.destroyContext(LwjglDisplay.java:160)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.deinitInThread(LwjglAbstractDisplay.java:196)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:237)
	at java.lang.Thread.run(Thread.java:748)


Exception: java.lang.AssertionError thrown from the UncaughtExceptionHandler in thread "jME3 Main"
```

**Comment by stephengold** [comment]
Perhaps the test is *supposed* to crash.

When @shadowislord wrote it, he did not include any documentation, but [his commit message](https://github.com/jMonkeyEngine/jmonkeyengine/commit/07a459555dfe39888e94a51cce1b2f451f306fe0) says "demonstrate what happens to a deleted texture when trying to use it with OpenGL"

If "what happens" is an assertion failure, then the issue is mainly one of documentation, not correctness. (I also need to test with assertions disabled!)

**Comment by stephengold** [comment]
With assertions disabled, the test prints a diagnostic message and completes normally:
```text
Apr 21, 2020 10:20:46 AM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.3.0-SNAPSHOT
 * Branch: v3.3
 * Git Hash: a667f5e
 * Build Date: 2020-04-21
Apr 21, 2020 10:20:46 AM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: null
 * Driver Version: null
 * Scaling Factor: 1
Apr 21, 2020 10:20:46 AM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
 * Vendor: NVIDIA Corporation
 * Renderer: GeForce GT 545/PCIe/SSE2
 * OpenGL Version: 4.6.0 NVIDIA 390.116
 * GLSL Version: 4.60 NVIDIA
 * Profile: Compatibility
Apr 21, 2020 10:20:47 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio Renderer Information
 * Device: OpenAL Soft
 * Vendor: OpenAL Community
 * Renderer: OpenAL Soft
 * Version: 1.1 ALSOFT 1.15.1
 * Supported channels: 64
 * ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
 * AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
Apr 21, 2020 10:20:47 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
Apr 21, 2020 10:20:47 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio effect extension version: 1.0
Apr 21, 2020 10:20:47 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio max auxiliary sends: 4
Assiging texture to deleted object!

BUILD SUCCESSFUL in 22s
```

**Comment by stephengold** [comment]
I added some documentation at 15e3acb .

**Comment by stephengold** [comment]
This example threw `AssertionFailure` as far back as JME 3.1, so I assume that's intentional.

**Comment by pspeed42** [comment]
It should definitely fail.  Using an object after destroying it is bad news... whether it's failing the right place or not remains to be seen.  It's unfortunate that it wasn't documented a little better.

**Comment by stephengold** [comment]
If we want the test to *always* fail, we should change the assertion into something stronger.

**Comment by stephengold** [comment]
Note that with LWJGL3 on Linux, I get both an assertion failure and a JVM crash:
```text
Assigning texture to deleted object!
Apr 23, 2020 1:03:37 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[main,5,main]
java.lang.AssertionError
	at com.jme3.util.NativeObjectManager.deleteNativeObject(NativeObjectManager.java:127)
	at com.jme3.util.NativeObjectManager.deleteAllObjects(NativeObjectManager.java:204)
	at com.jme3.renderer.opengl.GLRenderer.cleanup(GLRenderer.java:649)
	at com.jme3.system.lwjgl.LwjglWindow.destroyContext(LwjglWindow.java:420)
	at com.jme3.system.lwjgl.LwjglWindow.deinitInThread(LwjglWindow.java:609)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:643)
	at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:466)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:463)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:424)
	at com.jme3.app.SimpleApplication.start(SimpleApplication.java:127)
	at jme3test.app.TestUseAfterFree.main(TestUseAfterFree.java:49)

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1470672660, pid=17011, tid=0x00007f14e26b1700
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [liblwjgl.so+0x3c660]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/sgold/Git/jmonkeyengine/jme3-examples/hs_err_pid17011.log
```

The stack trace in hs_err_pid17011.log looks like so:
```text
Stack: [0x00007f14e25b2000,0x00007f14e26b2000],  sp=0x00007f14e26b04b8,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [liblwjgl.so+0x3c660]
j  org.lwjgl.system.dyncall.DynCallback.dcbGetUserData(J)J+12
j  org.lwjgl.system.Callback.free(J)V+12
j  org.lwjgl.system.Callback.free()V+4
j  org.lwjgl.system.NativeResource.close()V+1
j  com.jme3.input.lwjgl.GlfwMouseInput.closeCallbacks()V+4
j  com.jme3.input.lwjgl.GlfwMouseInput.destroy()V+12
j  com.jme3.app.LegacyApplication.destroyInput()V+11
j  com.jme3.app.LegacyApplication.destroy()V+8
j  com.jme3.system.lwjgl.LwjglWindow.deinitInThread()V+4
j  com.jme3.system.lwjgl.LwjglWindow.lambda$initInThread$11(Ljava/lang/Thread;Ljava/lang/Throwable;)V+43
j  com.jme3.system.lwjgl.LwjglWindow$$Lambda$27.uncaughtException(Ljava/lang/Thread;Ljava/lang/Throwable;)V+6
j  java.lang.Thread.dispatchUncaughtException(Ljava/lang/Throwable;)V+6
v  ~StubRoutines::call_stub
```
