### ISSUE TITLE
PBRLighting shader compilation error on macOS with OpenGL2 - Invalid call of undeclared identifier 'textureCubeLod'

### ISSUE THREAD

**Issue by rvandoosselaer** [jMonkeyEngine/jmonkeyengine#1356]
Testing 3.3.1 release candidate on macOS with OpenGL2.

When running TestPBRLighting:
```
Apr 21, 2020 10:13:39 AM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.3.0-SNAPSHOT
 * Branch: v3.3
 * Git Hash: a150deb
 * Build Date: 2020-04-21
Apr 21, 2020 10:13:39 AM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: null
 * Driver Version: null
 * Scaling Factor: 1
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jme3.util.ReflectionAllocator (file:/Users/remy/Projects/jMonkeyEngine/jmonkeyengine/jme3-core/build/libs/jme3-core-3.3.0-SNAPSHOT.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.jme3.util.ReflectionAllocator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Apr 21, 2020 10:13:39 AM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
 * Vendor: ATI Technologies Inc.
 * Renderer: AMD Radeon Pro Vega 20 OpenGL Engine
 * OpenGL Version: 2.1 ATI-2.11.21
 * GLSL Version: 1.20
 * Profile: Compatibility
Apr 21, 2020 10:13:40 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio Renderer Information
 * Device: MacBook Pro Speakers
 * Vendor: Apple Computer Inc.
 * Renderer: Software
 * Version: 1.1
 * Supported channels: 64
 * ALC extensions: ALC_EXT_CAPTURE ALC_ENUMERATION_EXT ALC_EXT_MAC_OSX ALC_EXT_ASA ALC_EXT_ASA_DISTORTION ALC_EXT_ASA_ROGER_BEEP
 * AL extensions: AL_EXT_OFFSET AL_EXT_LINEAR_DISTANCE AL_EXT_EXPONENT_DISTANCE AL_EXT_float32 AL_EXT_STATIC_BUFFER AL_EXT_SOURCE_NOTIFICATIONS AL_EXT_SOURCE_SPATIALIZATION
Apr 21, 2020 10:13:40 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
Apr 21, 2020 10:13:40 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: OpenAL EFX not available! Audio effects won't work.
Apr 21, 2020 10:13:44 AM com.jme3.material.Material checkSetParam
WARNING: Material parameter being set: Texture with type Texture2D doesn't match definition types TextureCubeMap
Apr 21, 2020 10:13:44 AM com.jme3.material.Material checkTextureParamColorSpace
WARNING: The texture Textures/Sky/Path.hdr has linear color space, but the material parameter Texture specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
Apr 21, 2020 10:13:45 AM com.jme3.material.Material checkTextureParamColorSpace
WARNING: The texture Models/Tank/Tank_Occ_Rough_Metal.png has linear color space, but the material parameter LightMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
Apr 21, 2020 10:13:45 AM com.jme3.renderer.opengl.GLRenderer updateShaderSourceData
WARNING: Bad compile of:
1	#version 110
2	#define FRAGMENT_SHADER 1
3	
4	uniform samplerCube m_CubeMap;
5	
6	varying vec3 Reflect_refVec;
7	
8	void main() {
9			vec4 Global_color = vec4(1.0);
10	
11	
12		//EnvMapping : Begin
13		vec3 EnvMapping_refVec;
14		EnvMapping_refVec = Reflect_refVec;
15		vec4 EnvMapping_color;
16	
17	        //@input vec3 EnvMapping_refVec the reflection vector
18	    //@input samplerCube m_CubeMap the cube map
19	    //@output vec4 EnvMapping_color the output EnvMapping_color
20	
21	    #ifdef GL_ES
22	        #ifdef GL_EXT_shader_texture_lod
23	            EnvMapping_color = textureCubeLodEXT(m_CubeMap, EnvMapping_refVec, 0.0);
24	        #else
25	            EnvMapping_color = textureCube(m_CubeMap, EnvMapping_refVec);
26	        #endif
27	    #else
28	        EnvMapping_color = textureCubeLod(m_CubeMap, EnvMapping_refVec, 0.0);
29	    #endif
30		Global_color = EnvMapping_color;
31		//EnvMapping : End
32	
33		gl_FragColor = Global_color;
34	}

Apr 21, 2020 10:13:45 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.renderer.RendererException: compile error in: ShaderSource[name=Default.frag, defines, type=Fragment, language=GLSL100]
ERROR: 0:28: Invalid call of undeclared identifier 'textureCubeLod'

	at com.jme3.renderer.opengl.GLRenderer.updateShaderSourceData(GLRenderer.java:1485)
	at com.jme3.renderer.opengl.GLRenderer.updateShaderData(GLRenderer.java:1512)
	at com.jme3.renderer.opengl.GLRenderer.setShader(GLRenderer.java:1576)
	at com.jme3.material.logic.DefaultTechniqueDefLogic.render(DefaultTechniqueDefLogic.java:94)
	at com.jme3.material.Technique.render(Technique.java:166)
	at com.jme3.material.Material.render(Material.java:1026)
	at com.jme3.renderer.RenderManager.renderGeometry(RenderManager.java:614)
	at com.jme3.renderer.queue.RenderQueue.renderGeometryList(RenderQueue.java:266)
	at com.jme3.renderer.queue.RenderQueue.renderQueue(RenderQueue.java:305)
	at com.jme3.renderer.RenderManager.renderViewPortQueues(RenderManager.java:877)
	at com.jme3.renderer.RenderManager.flushQueue(RenderManager.java:779)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1108)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:272)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:153)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:234)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by riccardobl** [comment]
It is an issue that affects only the shader nodes

**Comment by rvandoosselaer** [comment]
Yes. In this case it’s triggered by using the LightDebugState.

**Comment by stephengold** [comment]
Please describe how to reproduce this issue.

**Comment by stephengold** [comment]
This could be a duplicate of issue #1329

**Comment by rvandoosselaer** [comment]
It seems like the same issue indeed. The missing `textureCubeLod` function. I'll close this and update the linked issue with more info.
