### ISSUE TITLE
OPENGL40 + ArmatureDebugAppState + assertions enabled = OpenGLException

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1360]
Testing a 3.3.1 release candidate (commit = 4b62b70 ) on Mint Linux with assertions enabled.

The `TestAnimMigration` app in jme3-examples crashed shortly after launch:
```text
Apr 22, 2020 12:47:06 PM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.3.0-SNAPSHOT
 * Branch: v3.3
 * Git Hash: 4b62b70
 * Build Date: 2020-04-22
Apr 22, 2020 12:47:06 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: null
 * Driver Version: null
 * Scaling Factor: 1
Apr 22, 2020 12:47:06 PM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
 * Vendor: NVIDIA Corporation
 * Renderer: GeForce GT 545/PCIe/SSE2
 * OpenGL Version: 4.0.0 NVIDIA 390.116
 * GLSL Version: 4.00 NVIDIA via Cg compiler
 * Profile: Core
Apr 22, 2020 12:47:06 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio Renderer Information
 * Device: OpenAL Soft
 * Vendor: OpenAL Community
 * Renderer: OpenAL Soft
 * Version: 1.1 ALSOFT 1.15.1
 * Supported channels: 64
 * ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
 * AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
Apr 22, 2020 12:47:06 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
Apr 22, 2020 12:47:06 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio effect extension version: 1.0
Apr 22, 2020 12:47:06 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio max auxiliary sends: 4
Apr 22, 2020 12:47:07 PM com.jme3.anim.SkinningControl controlRender
INFO: Hardware skinning engaged for JaimeGeom-ogremesh (Node)
Apr 22, 2020 12:47:07 PM com.jme3.app.LegacyApplication handleError
SEVERE: An OpenGL error has occurred!
org.lwjgl.opengl.OpenGLException: Invalid value (1281)
	at org.lwjgl.opengl.Util.checkGLError(Util.java:59)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.checkGLError(LwjglAbstractDisplay.java:138)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:159)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:234)
	at java.lang.Thread.run(Thread.java:748)
```

If I comment out the line that attaches the `ArmatureDebugAppState`, the app launches successfully.

**Comment by stephengold** [comment]
Current `master` branch (commit= 917509a ) doesn't have this issue. Why?

**Comment by stephengold** [comment]
I'm having trouble reproducing this issue, even at commit  4b62b70 . Perhaps it was caused by a race condition or some bad state left over from a previous test.

**Comment by stephengold** [comment]
Weird. Closing this because it's not reproducible.

**Comment by stephengold** [comment]
Now I'm seeing it again, running `TestAnimMigration` on Windows.

**Comment by stephengold** [comment]
Applying `setRenderer(AppSettings.LWJGL_OPENGL40);` on the `AppSettings` triggers the issue. The setting apparently occurred in `TestTessellationShader`, and the Engine helpfully "remembered" it until I later ran `TestAnimMigration` many minutes later.

**Comment by stephengold** [comment]
I added `settings.putBoolean("GraphicsDebug", true);` and obtained the following debug output:
```text
[JME3] OpenGL debug message
       ID: 131185
       Source: API
       Type: OTHER
       Severity: null
       Message: Buffer detailed info: Buffer object 1 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at com.jme3.system.lwjgl.LwjglGLDebugOutputHandler.handleMessage(LwjglGLDebugOutputHandler.java:76)
	at org.lwjgl.opengl.GL15.nglBufferData(Native Method)
	at org.lwjgl.opengl.GL15.glBufferData(GL15.java:156)
	at com.jme3.renderer.lwjgl.LwjglGL.glBufferData(LwjglGL.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jme3.renderer.opengl.GLDebug.invoke(GLDebug.java:107)
	at com.sun.proxy.$Proxy0.glBufferData(Unknown Source)
	at com.jme3.renderer.opengl.GLRenderer.updateBufferData(GLRenderer.java:2688)
	at com.jme3.renderer.RenderManager.preloadScene(RenderManager.java:670)
	at com.jme3.renderer.RenderManager.preloadScene(RenderManager.java:654)
	at com.jme3.anim.SkinningControl.testHardwareSupported(SkinningControl.java:175)
	at com.jme3.anim.SkinningControl.controlRender(SkinningControl.java:283)
	at com.jme3.scene.control.AbstractControl.render(AbstractControl.java:118)
	at com.jme3.scene.Spatial.runControlRender(Spatial.java:757)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:721)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
	at com.jme3.renderer.RenderManager.renderScene(RenderManager.java:710)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1096)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:272)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:153)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:234)
	at java.lang.Thread.run(Thread.java:748)
[JME3] OpenGL debug message
       ID: 131185
       Source: API
       Type: OTHER
       Severity: null
       Message: Buffer detailed info: Buffer object 2 (bound to GL_ELEMENT_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at com.jme3.system.lwjgl.LwjglGLDebugOutputHandler.handleMessage(LwjglGLDebugOutputHandler.java:76)
	at org.lwjgl.opengl.GL15.nglBufferData(Native Method)
	at org.lwjgl.opengl.GL15.glBufferData(GL15.java:170)
	at com.jme3.renderer.lwjgl.LwjglGL.glBufferData(LwjglGL.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jme3.renderer.opengl.GLDebug.invoke(GLDebug.java:107)
	at com.sun.proxy.$Proxy0.glBufferData(Unknown Source)
	at com.jme3.renderer.opengl.GLRenderer.updateBufferData(GLRenderer.java:2681)
	at com.jme3.renderer.RenderManager.preloadScene(RenderManager.java:670)
	at com.jme3.renderer.RenderManager.preloadScene(RenderManager.java:654)
	at com.jme3.anim.SkinningControl.testHardwareSupported(SkinningControl.java:175)
	at com.jme3.anim.SkinningControl.controlRender(SkinningControl.java:283)
	at com.jme3.scene.control.AbstractControl.render(AbstractControl.java:118)
	at com.jme3.scene.Spatial.runControlRender(Spatial.java:757)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:721)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
	at com.jme3.renderer.RenderManager.renderScene(RenderManager.java:710)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1096)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:272)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:153)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:234)
	at java.lang.Thread.run(Thread.java:748)
[JME3] OpenGL debug message
       ID: 131185
       Source: API
       Type: OTHER
       Severity: null
       Message: Buffer detailed info: Buffer object 3 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at com.jme3.system.lwjgl.LwjglGLDebugOutputHandler.handleMessage(LwjglGLDebugOutputHandler.java:76)
	at org.lwjgl.opengl.GL15.nglBufferData(Native Method)
	at org.lwjgl.opengl.GL15.glBufferData(GL15.java:142)
	at com.jme3.renderer.lwjgl.LwjglGL.glBufferData(LwjglGL.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jme3.renderer.opengl.GLDebug.invoke(GLDebug.java:107)
	at com.sun.proxy.$Proxy0.glBufferData(Unknown Source)
	at com.jme3.renderer.opengl.GLRenderer.updateBufferData(GLRenderer.java:2677)
	at com.jme3.renderer.RenderManager.preloadScene(RenderManager.java:670)
	at com.jme3.renderer.RenderManager.preloadScene(RenderManager.java:654)
	at com.jme3.anim.SkinningControl.testHardwareSupported(SkinningControl.java:175)
	at com.jme3.anim.SkinningControl.controlRender(SkinningControl.java:283)
	at com.jme3.scene.control.AbstractControl.render(AbstractControl.java:118)
	at com.jme3.scene.Spatial.runControlRender(Spatial.java:757)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:721)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
	at com.jme3.renderer.RenderManager.renderScene(RenderManager.java:710)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1096)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:272)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:153)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:234)
	at java.lang.Thread.run(Thread.java:748)
[JME3] OpenGL debug message
       ID: 131185
       Source: API
       Type: OTHER
       Severity: null
       Message: Buffer detailed info: Buffer object 4 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at com.jme3.system.lwjgl.LwjglGLDebugOutputHandler.handleMessage(LwjglGLDebugOutputHandler.java:76)
	at org.lwjgl.opengl.GL15.nglBufferData(Native Method)
	at org.lwjgl.opengl.GL15.glBufferData(GL15.java:156)
	at com.jme3.renderer.lwjgl.LwjglGL.glBufferData(LwjglGL.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jme3.renderer.opengl.GLDebug.invoke(GLDebug.java:107)
	at com.sun.proxy.$Proxy0.glBufferData(Unknown Source)
	at com.jme3.renderer.opengl.GLRenderer.updateBufferData(GLRenderer.java:2688)
	at com.jme3.renderer.RenderManager.preloadScene(RenderManager.java:670)
	at com.jme3.renderer.RenderManager.preloadScene(RenderManager.java:654)
	at com.jme3.anim.SkinningControl.testHardwareSupported(SkinningControl.java:175)
	at com.jme3.anim.SkinningControl.controlRender(SkinningControl.java:283)
	at com.jme3.scene.control.AbstractControl.render(AbstractControl.java:118)
	at com.jme3.scene.Spatial.runControlRender(Spatial.java:757)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:721)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
	at com.jme3.renderer.RenderManager.renderScene(RenderManager.java:710)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1096)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:272)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:153)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:234)
	at java.lang.Thread.run(Thread.java:748)
[JME3] OpenGL debug message
       ID: 131185
       Source: API
       Type: OTHER
       Severity: null
       Message: Buffer detailed info: Buffer object 5 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at com.jme3.system.lwjgl.LwjglGLDebugOutputHandler.handleMessage(LwjglGLDebugOutputHandler.java:76)
	at org.lwjgl.opengl.GL15.nglBufferData(Native Method)
	at org.lwjgl.opengl.GL15.glBufferData(GL15.java:156)
	at com.jme3.renderer.lwjgl.LwjglGL.glBufferData(LwjglGL.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jme3.renderer.opengl.GLDebug.invoke(GLDebug.java:107)
	at com.sun.proxy.$Proxy0.glBufferData(Unknown Source)
	at com.jme3.renderer.opengl.GLRenderer.updateBufferData(GLRenderer.java:2688)
	at com.jme3.renderer.RenderManager.preloadScene(RenderManager.java:670)
	at com.jme3.renderer.RenderManager.preloadScene(RenderManager.java:654)
	at com.jme3.anim.SkinningControl.testHardwareSupported(SkinningControl.java:175)
	at com.jme3.anim.SkinningControl.controlRender(SkinningControl.java:283)
	at com.jme3.scene.control.AbstractControl.render(AbstractControl.java:118)
	at com.jme3.scene.Spatial.runControlRender(Spatial.java:757)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:721)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
	at com.jme3.renderer.RenderManager.renderScene(RenderManager.java:710)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1096)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:272)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:153)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:234)
	at java.lang.Thread.run(Thread.java:748)
[JME3] OpenGL debug message
       ID: 131185
       Source: API
       Type: OTHER
       Severity: null
       Message: Buffer detailed info: Buffer object 6 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at com.jme3.system.lwjgl.LwjglGLDebugOutputHandler.handleMessage(LwjglGLDebugOutputHandler.java:76)
	at org.lwjgl.opengl.GL15.nglBufferData(Native Method)
	at org.lwjgl.opengl.GL15.glBufferData(GL15.java:156)
	at com.jme3.renderer.lwjgl.LwjglGL.glBufferData(LwjglGL.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jme3.renderer.opengl.GLDebug.invoke(GLDebug.java:107)
	at com.sun.proxy.$Proxy0.glBufferData(Unknown Source)
	at com.jme3.renderer.opengl.GLRenderer.updateBufferData(GLRenderer.java:2688)
	at com.jme3.renderer.RenderManager.preloadScene(RenderManager.java:670)
	at com.jme3.renderer.RenderManager.preloadScene(RenderManager.java:654)
	at com.jme3.anim.SkinningControl.testHardwareSupported(SkinningControl.java:175)
	at com.jme3.anim.SkinningControl.controlRender(SkinningControl.java:283)
	at com.jme3.scene.control.AbstractControl.render(AbstractControl.java:118)
	at com.jme3.scene.Spatial.runControlRender(Spatial.java:757)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:721)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
	at com.jme3.renderer.RenderManager.renderScene(RenderManager.java:710)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1096)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:272)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:153)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:234)
	at java.lang.Thread.run(Thread.java:748)
[JME3] OpenGL debug message
       ID: 131185
       Source: API
       Type: OTHER
       Severity: null
       Message: Buffer detailed info: Buffer object 7 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at com.jme3.system.lwjgl.LwjglGLDebugOutputHandler.handleMessage(LwjglGLDebugOutputHandler.java:76)
	at org.lwjgl.opengl.GL15.nglBufferData(Native Method)
	at org.lwjgl.opengl.GL15.glBufferData(GL15.java:156)
	at com.jme3.renderer.lwjgl.LwjglGL.glBufferData(LwjglGL.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jme3.renderer.opengl.GLDebug.invoke(GLDebug.java:107)
	at com.sun.proxy.$Proxy0.glBufferData(Unknown Source)
	at com.jme3.renderer.opengl.GLRenderer.updateBufferData(GLRenderer.java:2688)
	at com.jme3.renderer.RenderManager.preloadScene(RenderManager.java:670)
	at com.jme3.renderer.RenderManager.preloadScene(RenderManager.java:654)
	at com.jme3.anim.SkinningControl.testHardwareSupported(SkinningControl.java:175)
	at com.jme3.anim.SkinningControl.controlRender(SkinningControl.java:283)
	at com.jme3.scene.control.AbstractControl.render(AbstractControl.java:118)
	at com.jme3.scene.Spatial.runControlRender(Spatial.java:757)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:721)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
	at com.jme3.renderer.RenderManager.renderScene(RenderManager.java:710)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1096)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:272)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:153)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:234)
	at java.lang.Thread.run(Thread.java:748)
Apr 23, 2020 5:20:18 PM com.jme3.anim.SkinningControl controlRender
INFO: Hardware skinning engaged for JaimeGeom-ogremesh (Node)
[JME3] OpenGL debug message
       ID: 1281
       Source: API
       Type: ERROR
       Severity: HIGH
       Message: GL_INVALID_VALUE error generated. Operation is not valid from a preview context.
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at com.jme3.system.lwjgl.LwjglGLDebugOutputHandler.handleMessage(LwjglGLDebugOutputHandler.java:76)
	at org.lwjgl.opengl.GL11.nglLineWidth(Native Method)
	at org.lwjgl.opengl.GL11.glLineWidth(GL11.java:1983)
	at com.jme3.renderer.lwjgl.LwjglGL.glLineWidth(LwjglGL.java:275)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jme3.renderer.opengl.GLDebug.invoke(GLDebug.java:107)
	at com.sun.proxy.$Proxy0.glLineWidth(Unknown Source)
	at com.jme3.renderer.opengl.GLRenderer.applyRenderState(GLRenderer.java:911)
	at com.jme3.material.Material.updateRenderState(Material.java:875)
	at com.jme3.material.Material.render(Material.java:1005)
	at com.jme3.renderer.RenderManager.renderGeometry(RenderManager.java:614)
	at com.jme3.renderer.queue.RenderQueue.renderGeometryList(RenderQueue.java:266)
	at com.jme3.renderer.queue.RenderQueue.renderQueue(RenderQueue.java:305)
	at com.jme3.renderer.RenderManager.renderViewPortQueues(RenderManager.java:877)
	at com.jme3.renderer.RenderManager.flushQueue(RenderManager.java:779)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1108)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:272)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:153)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:234)
	at java.lang.Thread.run(Thread.java:748)
Apr 23, 2020 5:20:18 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.renderer.RendererException: An OpenGL error occurred - Invalid numeric argument (Error Code: 1281)
	at com.jme3.renderer.opengl.GLDebug.checkError(GLDebug.java:101)
	at com.jme3.renderer.opengl.GLDebug.invoke(GLDebug.java:113)
	at com.sun.proxy.$Proxy0.glLineWidth(Unknown Source)
	at com.jme3.renderer.opengl.GLRenderer.applyRenderState(GLRenderer.java:911)
	at com.jme3.material.Material.updateRenderState(Material.java:875)
	at com.jme3.material.Material.render(Material.java:1005)
	at com.jme3.renderer.RenderManager.renderGeometry(RenderManager.java:614)
	at com.jme3.renderer.queue.RenderQueue.renderGeometryList(RenderQueue.java:266)
	at com.jme3.renderer.queue.RenderQueue.renderQueue(RenderQueue.java:305)
	at com.jme3.renderer.RenderManager.renderViewPortQueues(RenderManager.java:877)
	at com.jme3.renderer.RenderManager.flushQueue(RenderManager.java:779)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1108)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:272)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:153)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:234)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by riccardobl** [comment]
The problem here is that glLineWidth with values >1 is an optional and now deprecated feature.
It should be possible to query GL_ALIASED_LINE_WIDTH_RANGE to get the range, however the returned range seems to be invalid with my drivers...
```java
floatBuf16.rewind();
gl.glGetFloat(GL.GL_ALIASED_LINE_WIDTH_RANGE,floatBuf16);       
System.out.println(floatBuf16.get(0));
System.out.println(floatBuf16.get(1));
```
```
1.0
2048.0
```
```
 * Renderer: Radeon RX 580 Series (POLARIS10, DRM 3.36.0, 5.5.0-050500-generic, LLVM 10.0.0)
 * OpenGL Version: 4.6 (Core Profile) Mesa 20.1.0-devel (git-4d57a27 2020-02-22 bionic-oibaf-ppa)
```

An alternative workaround would be to just limit width to 1 whenever a core profile is enabled.

**Comment by stephengold** [comment]
Thanks for that analysis, @riccardobl !

**Comment by stephengold** [comment]
My preference would be to specify `setLineWidth(1)` in the `ArmatureDebugger`. My only hesitation is that I'm (once again) having difficulty reproducing the issue.

At some later date, we may want to add an interface to allow users to configure the line widths used in `ArmatureDebugger`.

**Comment by stephengold** [comment]
I discovered that the crash only occurs with jme3-lwjgl, not with jme3-lwjgl3. I'm ready to commit a fix to master.

**Comment by stephengold** [comment]
Solved in master branch at 9751e23cd71966bc0074d399b68a6e72e3cc485d and in v3.3 branch at 618e890ddbbdfdc4afc0f11388d116a8f24ecebc .

**Comment by riccardobl** [comment]
What fix?

**Comment by riccardobl** [comment]
> I discovered that the crash only occurs with jme3-lwjgl, not with jme3-lwjgl3. I'm ready to commit a fix to master.

It occurs also with lwjgl3 for me.
