### ISSUE TITLE
JmeDesktopSystem depends on LWJGL v2

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1362]
None of the test apps in `jme3test.awt` package work with LWJGL v3, partly due to a hard-coded dependency on `com.jme3.system.lwjgl.LwjglCanvas` in `JmeDesktopSystem.newContextLwjgl()`:

https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-desktop/src/main/java/com/jme3/system/JmeDesktopSystem.java#L199

Typical stack trace:
```text
INFO JmeDesktopSystem 1:20:29 PM Running on jMonkeyEngine 3.3.0-SNAPSHOT
 * Branch: v3.3
 * Git Hash: 4b62b70
 * Build Date: 2020-04-23
SEVERE JmeDesktopSystem 1:20:29 PM CRITICAL ERROR: Context class is missing!
Make sure jme3_lwjgl-ogl is on the classpath.
java.lang.ClassNotFoundException: com.jme3.system.lwjgl.LwjglCanvas
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.jme3.system.JmeDesktopSystem.newContextLwjgl(JmeDesktopSystem.java:196)
	at com.jme3.system.JmeDesktopSystem.newContext(JmeDesktopSystem.java:279)
	at com.jme3.system.JmeSystem.newContext(JmeSystem.java:159)
	at com.jme3.app.LegacyApplication.createCanvas(LegacyApplication.java:510)
	at jme3test.awt.TestCanvas.createCanvas(TestCanvas.java:217)
	at jme3test.awt.TestCanvas.main(TestCanvas.java:248)
Exception in thread "main" java.lang.NullPointerException
	at com.jme3.system.JmeDesktopSystem.newContext(JmeDesktopSystem.java:280)
	at com.jme3.system.JmeSystem.newContext(JmeSystem.java:159)
	at com.jme3.app.LegacyApplication.createCanvas(LegacyApplication.java:510)
	at jme3test.awt.TestCanvas.createCanvas(TestCanvas.java:217)
	at jme3test.awt.TestCanvas.main(TestCanvas.java:248)
```

**Comment by stephengold** [comment]
Closing as a duplicate of #1192
