### ISSUE TITLE
The required native library 'bulletjme' was not found in the classpath via 'native/osx/x86_64/libbulletjme.dylib'

### ISSUE THREAD

**Issue by bewithme** [jMonkeyEngine/jmonkeyengine#1433]
* Branch: unknown
 * Git Hash: 
 * Build Date: 2020-11-24
Exception in thread "main" java.lang.UnsatisfiedLinkError: The required native library 'bulletjme' was not found in the classpath via 'native/osx/x86_64/libbulletjme.dylib'. Error message: no bulletjme in java.library.path: [/Users/wenfengxu/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at com.jme3.system.NativeLibraryLoader.loadNativeLibrary(NativeLibraryLoader.java:598)
	at com.jme3.system.JmeDesktopSystem.initialize(JmeDesktopSystem.java:351)
	at com.jme3.system.JmeDesktopSystem.newContext(JmeDesktopSystem.java:273)
	at com.jme3.system.JmeSystem.newContext(JmeSystem.java:159)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:479)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:441)
	at com.jme3.app.SimpleApplication.start(SimpleApplication.java:128)
	at jme3test.helloworld.HelloJME3.main(HelloJME3.java:50)

> Task :jme3-examples:HelloJME3.main() FAILED

Execution failed for task ':jme3-examples:HelloJME3.main()'.
> Process 'command '/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

**Comment by pspeed42** [comment]
For trouble shooting questions like this, you are more likely to get help soonest if you post to the forum.

**Comment by stephengold** [comment]
The first thing would be to make sure that the jme3-bullet-native library was included in the build.

If it was, please follow up to the JMonkeyEngine Forum at https://hub.jmonkeyengine.org
