### ISSUE TITLE
merging an infinite BoundingSphere with itself yields invalid result

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1459]
Issue discovered by the More Advanced Vehicles project, which occasionally caused an assert to fail:
```text
Jan 12, 2021 1:17:37 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[main,5,main]
java.lang.AssertionError
	at com.jme3.bounding.Intersection.intersect(Intersection.java:67)
	at com.jme3.bounding.BoundingSphere.intersectsBoundingBox(BoundingSphere.java:683)
	at com.jme3.bounding.BoundingBox.intersects(BoundingBox.java:595)
	at com.jme3.shadow.ShadowUtil$OccludersExtractor.process(ShadowUtil.java:428)
	at com.jme3.shadow.ShadowUtil$OccludersExtractor.addOccluders(ShadowUtil.java:368)
	at com.jme3.shadow.ShadowUtil.updateShadowCamera(ShadowUtil.java:501)
	at com.jme3.shadow.DirectionalLightShadowRenderer.getOccludersToRender(DirectionalLightShadowRenderer.java:194)
	at com.jme3.shadow.AbstractShadowRenderer.renderShadowMap(AbstractShadowRenderer.java:427)
	at com.jme3.shadow.AbstractShadowRenderer.postQueue(AbstractShadowRenderer.java:412)
	at com.jme3.shadow.AbstractShadowFilter.postQueue(AbstractShadowFilter.java:116)
	at com.jme3.post.FilterPostProcessor.postQueue(FilterPostProcessor.java:241)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1103)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:272)
	at com.jme3.system.lwjgl.LwjglWindow.runLoop(LwjglWindow.java:530)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:632)
	at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:466)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:463)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:424)
	at com.jme3.app.SimpleApplication.start(SimpleApplication.java:127)
	at com.jayfella.jme.vehicle.Main.main(Main.java:214)
```

Traced the issue back to `BoundingSphere.merge(float, Vector3f, BoundingSphere)`. For details see https://github.com/stephengold/jme-vehicles/issues/1

**Comment by stephengold** [comment]
Solved in "master" branch at 6b829c69e50a5d816dbe8161379fcde2bb0f8e6d.
