### ISSUE TITLE
crash in TestAppStates

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1542]
In v3.4.0-beta3, I hit an NPE while running TestAppStates, after I left-clicked on the flashing orange panel:

```text
May 08, 2021 1:57:29 PM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.4.0-SNAPSHOT
 * Branch: v3.4
 * Git Hash: fef5fc4
 * Build Date: 2021-05-08
May 08, 2021 1:57:30 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: null
 * Driver Version: null
 * Scaling Factor: 1
May 08, 2021 1:57:30 PM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
 * Vendor: NVIDIA Corporation
 * Renderer: GeForce GT 545/PCIe/SSE2
 * OpenGL Version: 4.6.0 NVIDIA 390.143
 * GLSL Version: 4.60 NVIDIA
 * Profile: Compatibility
May 08, 2021 1:57:30 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio Renderer Information
 * Device: OpenAL Soft
 * Vendor: OpenAL Community
 * Renderer: OpenAL Soft
 * Version: 1.1 ALSOFT 1.15.1
 * Supported channels: 64
 * ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
 * AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
May 08, 2021 1:57:30 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
May 08, 2021 1:57:30 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio effect extension version: 1.0
May 08, 2021 1:57:30 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio max auxiliary sends: 4
Initialize
May 08, 2021 1:57:30 PM com.jme3.scene.plugins.OBJLoader readLine
WARNING: smoothing groups are not supported, statement ignored: s
May 08, 2021 1:57:30 PM de.lessvoid.nifty.loaderv2.types.ScreenType create
WARNING: Missing ScreenController for screen [end] using DefaultScreenController() instead but this might not be what you want.
bind( start)
onStartScreen
May 08, 2021 1:57:44 PM de.lessvoid.nifty.NiftyMethodInvoker callMethod
WARNING: Exception in callMethod(public void jme3test.niftygui.TestNiftyGui.quit()) for [jme3test.niftygui.TestNiftyGui@7487f5ea]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at de.lessvoid.nifty.NiftyMethodInvoker.callMethod(NiftyMethodInvoker.java:157)
	at de.lessvoid.nifty.NiftyMethodInvoker.performInvoke(NiftyMethodInvoker.java:115)
	at de.lessvoid.nifty.Nifty$DelayedMethodInvoke.perform(Nifty.java:1481)
	at de.lessvoid.nifty.Nifty.invokeMethods(Nifty.java:1457)
	at de.lessvoid.nifty.Nifty.handleDynamicElements(Nifty.java:439)
	at de.lessvoid.nifty.Nifty.access$1600(Nifty.java:87)
	at de.lessvoid.nifty.Nifty$NiftyInputConsumerImpl.processEvent(Nifty.java:1727)
	at de.lessvoid.nifty.Nifty$NiftyInputConsumerImpl.processMouseEvent(Nifty.java:1665)
	at com.jme3.niftygui.InputSystemJme.handleMouseEvent(InputSystemJme.java:128)
	at com.jme3.niftygui.InputSystemJme.onMouseButtonEventQueued(InputSystemJme.java:236)
	at com.jme3.niftygui.InputSystemJme.forwardEvents(InputSystemJme.java:307)
	at de.lessvoid.nifty.Nifty.update(Nifty.java:368)
	at com.jme3.niftygui.InputSystemJme.endInput(InputSystemJme.java:117)
	at com.jme3.input.InputManager.processQueue(InputManager.java:859)
	at com.jme3.input.InputManager.update(InputManager.java:923)
	at com.jme3.app.LegacyApplication.update(LegacyApplication.java:774)
	at jme3test.app.state.TestAppStates.update(TestAppStates.java:82)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:160)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:201)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:242)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at jme3test.niftygui.TestNiftyGui.quit(TestNiftyGui.java:96)
	... 25 more
```

It's highly reproducible. From reading "Interface/Nifty/HelloJme.xml", I infer that a click is supposed to result in quitting the application.

**Comment by stephengold** [comment]
This issue has existed since at least JME v3.1, so if it's a regression, it must be a very old one. But since an example that throws an NPE is a bad example, I'll try to fix this.
