### ISSUE TITLE
OpenGLException in TestDebugShapes and TestMousePick

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1551]
```text
May 12, 2021 12:16:13 PM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.4.0-SNAPSHOT
 * Branch: v3.4
 * Git Hash: fef5fc4
 * Build Date: 2021-05-12
May 12, 2021 12:16:14 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: null
 * Driver Version: null
 * Scaling Factor: 1
May 12, 2021 12:16:14 PM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
 * Vendor: NVIDIA Corporation
 * Renderer: GeForce GT 545/PCIe/SSE2
 * OpenGL Version: 4.0.0 NVIDIA 390.143
 * GLSL Version: 4.00 NVIDIA via Cg compiler
 * Profile: Core
May 12, 2021 12:16:14 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio Renderer Information
 * Device: OpenAL Soft
 * Vendor: OpenAL Community
 * Renderer: OpenAL Soft
 * Version: 1.1 ALSOFT 1.15.1
 * Supported channels: 64
 * ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
 * AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
May 12, 2021 12:16:14 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
May 12, 2021 12:16:14 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio effect extension version: 1.0
May 12, 2021 12:16:14 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio max auxiliary sends: 4
May 12, 2021 12:16:14 PM com.jme3.app.LegacyApplication handleError
SEVERE: An OpenGL error has occurred!
org.lwjgl.opengl.OpenGLException: Invalid value (1281)
	at org.lwjgl.opengl.Util.checkGLError(Util.java:59)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.checkGLError(LwjglAbstractDisplay.java:145)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:166)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:201)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:242)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by stephengold** [comment]
I applied `AppSettings.setGraphicsDebug(true);` and was unable to reproduce this issue. Then I applied `AppSettings.setGraphicsDebug(false);` and I *still* was unable to repro.

**Comment by stephengold** [comment]
Okay, it's the old gotcha of persistent app settings, shared by multiple tests.

Apparently one of the tests I ran earlier (`TestTessellationShader`?) set the renderer to an atypical value (such as `LWJGL_OPENGL40`?) which breaks this test.

Here's the graphics-debug error message with LWJGL_OPENGL40:
```text
[JME3] OpenGL debug message
       ID: 1281
       Source: API
       Type: ERROR
       Severity: HIGH
       Message: GL_INVALID_VALUE error generated. Operation is not valid from a preview context.
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at com.jme3.system.lwjgl.LwjglGLDebugOutputHandler.handleMessage(LwjglGLDebugOutputHandler.java:76)
	at org.lwjgl.opengl.GL11.nglLineWidth(Native Method)
	at org.lwjgl.opengl.GL11.glLineWidth(GL11.java:1983)
	at com.jme3.renderer.lwjgl.LwjglGL.glLineWidth(LwjglGL.java:329)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jme3.renderer.opengl.GLDebug.invoke(GLDebug.java:107)
	at com.sun.proxy.$Proxy0.glLineWidth(Unknown Source)
	at com.jme3.renderer.opengl.GLRenderer.applyRenderState(GLRenderer.java:932)
	at com.jme3.material.Material.updateRenderState(Material.java:881)
	at com.jme3.material.Material.render(Material.java:1012)
	at com.jme3.renderer.RenderManager.renderGeometry(RenderManager.java:634)
	at com.jme3.renderer.queue.RenderQueue.renderGeometryList(RenderQueue.java:273)
	at com.jme3.renderer.queue.RenderQueue.renderQueue(RenderQueue.java:312)
	at com.jme3.renderer.RenderManager.renderViewPortQueues(RenderManager.java:897)
	at com.jme3.renderer.RenderManager.flushQueue(RenderManager.java:799)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1128)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1180)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:273)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:160)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:201)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:242)
	at java.lang.Thread.run(Thread.java:748)
```

Note that the arrow is being displayed with a line-width of 4 pixels. Commenting out the `setLineWidth(lineWidth);` seems to solve the issue.

**Comment by stephengold** [comment]
Ideally we would get the max line width from OpenGL, but see issue #1360 for why that fails.

**Comment by stephengold** [comment]
Issue #1555 would help address the underlying issue. For now, jme3-examples should stick to the default line width, which is 1.

**Comment by stephengold** [comment]
The issue crops up in `TestMousePick` and `TestLineWidthRenderState`. `TestLineWidthRenderState` can wait for #1555, but `TestMousePick` should stick with the default width.
