### ISSUE TITLE
error: `m_MorphWeights' undeclared when running TestMorph

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#1552]
```
May 13, 2021 10:15:15 AM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.4.0-SNAPSHOT
 * Branch: fix-morph-control
 * Git Hash: 3e9efe6
 * Build Date: 2021-05-13
May 13, 2021 10:15:16 AM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: null
 * Driver Version: null
 * Scaling Factor: 1
May 13, 2021 10:15:16 AM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
 * Vendor: Intel Open Source Technology Center
 * Renderer: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)
 * OpenGL Version: 3.3 (Core Profile) Mesa 21.0.1 - kisak-mesa PPA
 * GLSL Version: 3.30
 * Profile: Core
May 13, 2021 10:15:16 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio Renderer Information
 * Device: OpenAL Soft
 * Vendor: OpenAL Community
 * Renderer: OpenAL Soft
 * Version: 1.1 ALSOFT 1.15.1
 * Supported channels: 64
 * ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
 * AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
May 13, 2021 10:15:16 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
May 13, 2021 10:15:16 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio effect extension version: 1.0
May 13, 2021 10:15:16 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio max auxiliary sends: 4

May 13, 2021 10:15:16 AM com.jme3.renderer.opengl.GLRenderer updateShaderSourceData
WARNING: Bad compile of:
1	#version 150 core
2	#define VERTEX_SHADER 1
3	#define HAS_COLORMAP 1
4	#define HAS_POINTSIZE 1.0
5	#define NUM_MORPH_TARGETS 2
6	// -- begin import Common/ShaderLib/GLSLCompat.glsllib --
7	#if defined GL_ES
8	#  define hfloat highp float
9	#  define hvec2  highp vec2
10	#  define hvec3  highp vec3
11	#  define hvec4  highp vec4
12	#  define lfloat lowp float
13	#  define lvec2 lowp vec2
14	#  define lvec3 lowp vec3
15	#  define lvec4 lowp vec4
16	#else
17	#  define hfloat float
18	#  define hvec2  vec2
19	#  define hvec3  vec3
20	#  define hvec4  vec4
21	#  define lfloat float
22	#  define lvec2  vec2
23	#  define lvec3  vec3
24	#  define lvec4  vec4
25	#endif
26	
27	#if __VERSION__ >= 130
28	#  ifdef GL_ES
29	out highp vec4 outFragColor;
30	#  else
31	out vec4 outFragColor;
32	#endif
33	#  define texture1D texture
34	#  define texture2D texture
35	#  define texture3D texture
36	#  define textureCube texture
37	#  define texture2DLod textureLod
38	#  define textureCubeLod textureLod
39	#  define texture2DArray texture
40	#  if defined VERTEX_SHADER
41	#    define varying out
42	#    define attribute in
43	#  elif defined FRAGMENT_SHADER
44	#    define varying in
45	#    define gl_FragColor outFragColor
46	#  endif
47	#else
48	#  define isnan(val) !(val<0.0||val>0.0||val==0.0)
49	#endif
50	
51	#if __VERSION__ == 110
52	mat3 mat3_sub(mat4 m) {
53	  return mat3(m[0].xyz, m[1].xyz, m[2].xyz);
54	}
55	#else
56	 #define mat3_sub mat3
57	#endif
58	
59	#if __VERSION__ <= 140
60	float determinant(mat2 m) {
61	  return m[0][0] * m[1][1] - m[1][0] * m[0][1];
62	}
63	
64	float determinant(mat3 m) {
65	  return  + m[0][0] * (m[1][1] * m[2][2] - m[1][2] * m[2][1])
66	          - m[0][1] * (m[1][0] * m[2][2] - m[1][2] * m[2][0])
67	          + m[0][2] * (m[1][0] * m[2][1] - m[1][1] * m[2][0]);
68	}
69	#endif
70	
71	#if __VERSION__ <= 130
72	mat2 inverse(mat2 m) {
73	  return mat2(m[1][1], -m[0][1], -m[1][0], m[0][0]) / determinant(m);
74	}
75	
76	mat3 inverse(mat3 m) {
77	  return mat3(
78	    + (m[1][1] * m[2][2] - m[2][1] * m[1][2]),
79	    - (m[1][0] * m[2][2] - m[2][0] * m[1][2]),
80	    + (m[1][0] * m[2][1] - m[2][0] * m[1][1]),
81	    - (m[0][1] * m[2][2] - m[2][1] * m[0][2]),
82	    + (m[0][0] * m[2][2] - m[2][0] * m[0][2]),
83	    - (m[0][0] * m[2][1] - m[2][0] * m[0][1]),
84	    + (m[0][1] * m[1][2] - m[1][1] * m[0][2]),
85	    - (m[0][0] * m[1][2] - m[1][0] * m[0][2]),
86	    + (m[0][0] * m[1][1] - m[1][0] * m[0][1])) / determinant(m);
87	}
88	#endif
89	
90	// -- end import Common/ShaderLib/GLSLCompat.glsllib --
91	// -- begin import Common/ShaderLib/Skinning.glsllib --
92	#ifdef NUM_BONES
93	
94	#if NUM_BONES < 1 || NUM_BONES > 255
95	#error NUM_BONES must be between 1 and 255.
96	#endif
97	
98	#define NUM_WEIGHTS_PER_VERT 4
99	 
100	attribute vec4 inHWBoneWeight;
101	attribute vec4 inHWBoneIndex;
102	uniform mat4 m_BoneMatrices[NUM_BONES];
103	
104	void Skinning_Compute(inout vec4 position){
105	    if (inHWBoneWeight.x != 0.0) {
106	#if NUM_WEIGHTS_PER_VERT == 1
107	        position = m_BoneMatrices[int(inHWBoneIndex.x)] * position;
108	#else
109	        mat4 mat = mat4(0.0);
110	        mat += m_BoneMatrices[int(inHWBoneIndex.x)] * inHWBoneWeight.x;
111	        mat += m_BoneMatrices[int(inHWBoneIndex.y)] * inHWBoneWeight.y;
112	        mat += m_BoneMatrices[int(inHWBoneIndex.z)] * inHWBoneWeight.z;
113	        mat += m_BoneMatrices[int(inHWBoneIndex.w)] * inHWBoneWeight.w;
114	        position = mat * position;
115	#endif
116	    }
117	}
118	 
119	void Skinning_Compute(inout vec4 position, inout vec3 normal){
120	    if (inHWBoneWeight.x != 0.0) {
121	#if NUM_WEIGHTS_PER_VERT == 1
122	        position = m_BoneMatrices[int(inHWBoneIndex.x)] * position;
123	        normal = (mat3(m_BoneMatrices[int(inHWBoneIndex.x)][0].xyz,
124	                       m_BoneMatrices[int(inHWBoneIndex.x)][1].xyz,
125	                       m_BoneMatrices[int(inHWBoneIndex.x)][2].xyz) * normal);
126	#else
127	        mat4 mat = mat4(0.0);
128	        mat += m_BoneMatrices[int(inHWBoneIndex.x)] * inHWBoneWeight.x;
129	        mat += m_BoneMatrices[int(inHWBoneIndex.y)] * inHWBoneWeight.y;
130	        mat += m_BoneMatrices[int(inHWBoneIndex.z)] * inHWBoneWeight.z;
131	        mat += m_BoneMatrices[int(inHWBoneIndex.w)] * inHWBoneWeight.w;
132	        position = mat * position;
133	
134	        mat3 rotMat = mat3(mat[0].xyz, mat[1].xyz, mat[2].xyz);
135	        normal = rotMat * normal;
136	#endif
137	    }
138	}
139	 
140	void Skinning_Compute(inout vec4 position, inout vec3 normal, inout vec3 tangent){
141	    if (inHWBoneWeight.x != 0.0) {
142	#if NUM_WEIGHTS_PER_VERT == 1
143	        position = m_BoneMatrices[int(inHWBoneIndex.x)] * position;
144	        tangent = m_BoneMatrices[int(inHWBoneIndex.x)] * tangent;
145	        normal = (mat3(m_BoneMatrices[int(inHWBoneIndex.x)][0].xyz,
146	                       m_BoneMatrices[int(inHWBoneIndex.x)][1].xyz,
147	                       m_BoneMatrices[int(inHWBoneIndex.x)][2].xyz) * normal);
148	#else
149	        mat4 mat = mat4(0.0);
150	        mat += m_BoneMatrices[int(inHWBoneIndex.x)] * inHWBoneWeight.x;
151	        mat += m_BoneMatrices[int(inHWBoneIndex.y)] * inHWBoneWeight.y;
152	        mat += m_BoneMatrices[int(inHWBoneIndex.z)] * inHWBoneWeight.z;
153	        mat += m_BoneMatrices[int(inHWBoneIndex.w)] * inHWBoneWeight.w;
154	        position = mat * position;
155	
156	        mat3 rotMat = mat3(mat[0].xyz, mat[1].xyz, mat[2].xyz);
157	        tangent = rotMat * tangent;
158	        normal = rotMat * normal;
159	#endif
160	    }
161	}
162	
163	#endif
164	// -- end import Common/ShaderLib/Skinning.glsllib --
165	// -- begin import Common/ShaderLib/Instancing.glsllib --
166	// Instancing GLSL library.
167	// 
168	// When the INSTANCING define is set in the shader, 
169	// all global matrices are replaced with "instanced" versions.
170	// One exception is g_NormalMatrix which becomes unusable,
171	// instead the function ApplyNormalTransform is used to transform
172	// the normal and tangent vectors into world view space.
173	
174	// The world matrix and normal transform quaternion need to be passed
175	// as vertex attributes "inWorldMatrix" and "inNormalRotationQuaternion"
176	// respectively. 
177	// The VertexBuffers for those two attributes 
178	// need to be configured into instanced mode (VertexBuffer.setInstanced(true)). 
179	//  - inWorldMatrix should have 12 * numInstances floats.
180	//  - inNormalRotationQuaternion should have 4 * numInstances.
181	// Thus, instancing data occupies 4 vertex attributes (16 / 4 = 4).
182	// 
183	// The GL_ARB_draw_instanced and GL_ARB_instanced_arrays extensions 
184	// are required (OGL 3.3).
185	
186	uniform mat4 g_WorldMatrix;
187	uniform mat4 g_ViewMatrix;
188	uniform mat4 g_ProjectionMatrix;
189	uniform mat4 g_WorldViewMatrix;
190	uniform mat4 g_WorldViewProjectionMatrix;
191	uniform mat4 g_ViewProjectionMatrix;
192	uniform mat3 g_NormalMatrix;
193	uniform mat3 g_WorldNormalMatrix;
194	
195	#if defined INSTANCING
196	
197	// World Matrix + Normal Rotation Quaternion. 
198	// The World Matrix is the top 3 rows - 
199	//     since the bottom row is always 0,0,0,1 for this transform.
200	// The bottom row is the transpose of the inverse of WorldView Transform 
201	//     as a quaternion. i.e. g_NormalMatrix converted to a quaternion.
202	//
203	// Using a quaternion instead of a matrix here allows saving approximately
204	// 2 vertex attributes which now can be used for additional per-vertex data.
205	attribute mat4 inInstanceData;
206	
207	
208	
209	vec4 TransformWorld(vec4 position)
210	{
211	    // Extract the world matrix out of the instance data, leaving out the
212	    // quaternion at the end.
213	    mat4 worldMatrix = mat4(vec4(inInstanceData[0].xyz, 0.0),
214	    vec4(inInstanceData[1].xyz, 0.0),
215	    vec4(inInstanceData[2].xyz, 0.0),
216	    vec4(inInstanceData[3].xyz, 1.0));
217	    return (worldMatrix * position);
218	}
219	
220	vec4 TransformWorldView(vec4 position)
221	{
222	    return g_ViewMatrix * TransformWorld(position);
223	}
224	
225	vec4 TransformWorldViewProjection(vec4 position)
226	{
227	    return g_ViewProjectionMatrix * TransformWorld(position);
228	}
229	
230	vec3 TransformWorldNormal(vec3 vec) {
231	    vec4 quat = vec4(inInstanceData[0].w, inInstanceData[1].w,
232	                     inInstanceData[2].w, inInstanceData[3].w);
233	
234	    return vec + vec3(2.0) * cross(cross(vec, quat.xyz) + vec3(quat.w) * vec, quat.xyz);
235	}
236	
237	vec3 TransformNormal(vec3 vec)
238	{
239	    return (g_ViewMatrix * vec4(TransformWorldNormal(vec), 0.0)).xyz;
240	}
241	
242	// Prevent user from using g_** matrices which will have invalid data in this case.
243	#define g_WorldMatrix               Use_the_instancing_functions_for_this
244	#define g_WorldViewMatrix           Use_the_instancing_functions_for_this
245	#define g_WorldViewProjectionMatrix Use_the_instancing_functions_for_this
246	#define g_NormalMatrix              Use_the_instancing_functions_for_this
247	
248	#else
249	
250	vec4 TransformWorld(vec4 position)
251	{
252	    return g_WorldMatrix * position;
253	}
254	
255	vec4 TransformWorldView(vec4 position)
256	{
257	    return g_WorldViewMatrix * position;
258	}
259	
260	vec4 TransformWorldViewProjection(vec4 position)
261	{
262	    return g_WorldViewProjectionMatrix * position;
263	}
264	
265	vec3 TransformNormal(vec3 normal) {
266		return g_NormalMatrix * normal;
267	}
268	
269	vec3 TransformWorldNormal(vec3 normal) {
270	    return normalize(g_WorldNormalMatrix * normal);
271	}
272	
273	 
274	#endif
275	// -- end import Common/ShaderLib/Instancing.glsllib --
276	// -- begin import Common/ShaderLib/MorphAnim.glsllib --
277	/**
278	A glsllib that perform morph animation.
279	Note that it only handles morphing position, normals and tangents.
280	*/
281	#ifdef NUM_MORPH_TARGETS
282	    #define NUM_BUFFERS NUM_MORPH_TARGETS * NUM_TARGETS_BUFFERS
283	    #if (NUM_BUFFERS > 0)
284	        uniform float m_MorphWeights[NUM_MORPH_TARGETS];
285	        attribute vec3 inMorphTarget0;
286	    #endif
287	    #if (NUM_BUFFERS > 1)
288	        attribute vec3 inMorphTarget1;
289	    #endif
290	    #if (NUM_BUFFERS > 2)
291	        attribute vec3 inMorphTarget2;
292	    #endif
293	    #if (NUM_BUFFERS > 3)
294	        attribute vec3 inMorphTarget3;
295	    #endif
296	    #if (NUM_BUFFERS > 4)
297	        attribute vec3 inMorphTarget4;
298	    #endif
299	    #if (NUM_BUFFERS > 5)
300	        attribute vec3 inMorphTarget5;
301	    #endif
302	    #if (NUM_BUFFERS > 6)
303	        attribute vec3 inMorphTarget6;
304	    #endif
305	    #if (NUM_BUFFERS > 7)
306	        attribute vec3 inMorphTarget7;
307	    #endif
308	    #if (NUM_BUFFERS > 8)
309	        attribute vec3 inMorphTarget8;
310	    #endif
311	    #if (NUM_BUFFERS > 9)
312	        attribute vec3 inMorphTarget9;
313	    #endif
314	    #if (NUM_BUFFERS > 10)
315	        attribute vec3 inMorphTarget10;
316	    #endif
317	    #if (NUM_BUFFERS > 11)
318	        attribute vec3 inMorphTarget11;
319	    #endif
320	    #if (NUM_BUFFERS > 12)
321	        attribute vec3 inMorphTarget12;
322	    #endif
323	    #if (NUM_BUFFERS > 13)
324	        attribute vec3 inMorphTarget13;
325	    #endif
326	
327	    void Morph_Compute_Pos(inout vec4 pos){
328	        #if (NUM_TARGETS_BUFFERS == 1)
329	            #if (NUM_MORPH_TARGETS > 0)
330	                pos.xyz += m_MorphWeights[0] * inMorphTarget0;
331	            #endif
332	            #if (NUM_MORPH_TARGETS > 1)
333	                pos.xyz += m_MorphWeights[1] * inMorphTarget1;
334	            #endif
335	            #if (NUM_MORPH_TARGETS > 2)
336	                pos.xyz += m_MorphWeights[2] * inMorphTarget2;
337	            #endif
338	            #if (NUM_MORPH_TARGETS > 3)
339	                pos.xyz += m_MorphWeights[3] * inMorphTarget3;
340	            #endif
341	            #if (NUM_MORPH_TARGETS > 4)
342	                pos.xyz += m_MorphWeights[4] * inMorphTarget4;
343	            #endif
344	            #if (NUM_MORPH_TARGETS > 5)
345	                pos.xyz += m_MorphWeights[5] * inMorphTarget5;
346	            #endif
347	            #if (NUM_MORPH_TARGETS > 6)
348	                pos.xyz += m_MorphWeights[6] * inMorphTarget6;
349	            #endif
350	            #if (NUM_MORPH_TARGETS > 7)
351	                pos.xyz += m_MorphWeights[7] * inMorphTarget7;
352	            #endif
353	            #if (NUM_MORPH_TARGETS > 8)
354	                pos.xyz += m_MorphWeights[8] * inMorphTarget8;
355	            #endif
356	            #if (NUM_MORPH_TARGETS > 9)
357	                pos.xyz += m_MorphWeights[9] * inMorphTarget9;
358	            #endif
359	            #if (NUM_MORPH_TARGETS > 10)
360	                pos.xyz += m_MorphWeights[10] * inMorphTarget10;
361	            #endif
362	            #if (NUM_MORPH_TARGETS > 11)
363	                pos.xyz += m_MorphWeights[11] * inMorphTarget11;
364	            #endif
365	            #if (NUM_MORPH_TARGETS > 12)
366	                pos.xyz += m_MorphWeights[12] * inMorphTarget12;
367	            #endif
368	            #if (NUM_MORPH_TARGETS > 13)
369	                pos.xyz += m_MorphWeights[13] * inMorphTarget13;
370	            #endif
371	        #endif
372	    }
373	
374	    float Get_Inverse_Weights_Sum(){
375	        float sum = 0.0;
376	        for( int i = 0;i < NUM_MORPH_TARGETS; i++){
377	            sum += m_MorphWeights[i];
378	        }
379	        return 1.0 / max(1.0, sum);
380	    }
381	
382	    void Morph_Compute_Pos_Norm(inout vec4 pos, inout vec3 norm){
383	        #if (NUM_TARGETS_BUFFERS == 2)
384	            // weight sum may be over 1.0. It's totallyvalid for position
385	            // but for normals. the weights needs to be normalized.
386	            float invWeightsSum = Get_Inverse_Weights_Sum();
387	            #if (NUM_BUFFERS > 1)
388	                pos.xyz += m_MorphWeights[0] * inMorphTarget0;
389	                norm += m_MorphWeights[0] * invWeightsSum * inMorphTarget1;
390	            #endif
391	            #if (NUM_BUFFERS > 3)
392	                pos.xyz += m_MorphWeights[1] * inMorphTarget2;
393	                norm.xyz += m_MorphWeights[1] * invWeightsSum * inMorphTarget3;
394	            #endif
395	            #if (NUM_BUFFERS > 5)
396	                pos.xyz += m_MorphWeights[2] * inMorphTarget4;
397	                norm += m_MorphWeights[2] * invWeightsSum * inMorphTarget5;
398	            #endif
399	            #if (NUM_BUFFERS > 7)
400	                pos.xyz += m_MorphWeights[3] * inMorphTarget6;
401	                norm += m_MorphWeights[3] * invWeightsSum * inMorphTarget7;
402	            #endif
403	            #if (NUM_BUFFERS > 9)
404	                pos.xyz += m_MorphWeights[4] * inMorphTarget8;
405	                norm += m_MorphWeights[4] * invWeightsSum * inMorphTarget9;
406	            #endif
407	            #if (NUM_BUFFERS > 11)
408	                pos.xyz += m_MorphWeights[5] * inMorphTarget10;
409	                norm += m_MorphWeights[5] * invWeightsSum * inMorphTarget11;
410	            #endif
411	            #if (NUM_BUFFERS > 13)
412	                pos.xyz += m_MorphWeights[6] * inMorphTarget12;
413	                norm += m_MorphWeights[6] * invWeightsSum * inMorphTarget13;
414	            #endif
415	        #endif
416	    }
417	
418	    void Morph_Compute_Pos_Norm_Tan(inout vec4 pos, inout vec3 norm, inout vec3 tan){
419	        #if (NUM_TARGETS_BUFFERS == 3)
420	            // weight sum may be over 1.0. It's totallyvalid for position
421	            // but for normals. the weights needs to be normalized.
422	            float invWeightsSum = Get_Inverse_Weights_Sum();
423	            #if (NUM_BUFFERS > 2)
424	                float normWeight =  m_MorphWeights[0] * invWeightsSum;
425	                pos.xyz += m_MorphWeights[0] * inMorphTarget0;
426	                norm += normWeight * inMorphTarget1;
427	                tan += normWeight * inMorphTarget2;
428	            #endif
429	            #if (NUM_BUFFERS > 5)
430	                float normWeight =  m_MorphWeights[1] * invWeightsSum;
431	                pos.xyz += m_MorphWeights[1] * inMorphTarget3;
432	                norm += normWeight * inMorphTarget4;
433	                tan += normWeight * inMorphTarget5;
434	            #endif
435	            #if (NUM_BUFFERS > 8)
436	                float normWeight =  m_MorphWeights[2] * invWeightsSum;
437	                pos.xyz += m_MorphWeights[2] * inMorphTarget6;
438	                norm += normWeight * inMorphTarget7;
439	                tan += normWeight * inMorphTarget8;
440	            #endif
441	            #if (NUM_BUFFERS > 11)
442	                float normWeight =  m_MorphWeights[3] * invWeightsSum;
443	                pos.xyz += m_MorphWeights[3] * inMorphTarget9;
444	                norm += normWeight * inMorphTarget10;
445	                tan += normWeight * inMorphTarget11;
446	            #endif
447	        #endif
448	    }
449	
450	    void Morph_Compute(inout vec4 pos){
451	        #if (NUM_TARGETS_BUFFERS == 2)
452	            vec3 dummy_norm = vec3(0.0);
453	            Morph_Compute_Pos_Norm(pos, dummy_norm);
454	            return;
455	        #elif (NUM_TARGETS_BUFFERS == 3)
456	            vec3 dummy_norm = vec3(0.0);
457	            vec3 dummy_tan = vec3(0.0);
458	            Morph_Compute_Pos_Norm_Tan(pos, dummy_norm, dummy_tan);
459	            return;
460	        #endif
461	        Morph_Compute_Pos(pos);
462	    }
463	
464	    void Morph_Compute(inout vec4 pos, inout vec3 norm){
465	        #if (NUM_TARGETS_BUFFERS == 1)
466	            Morph_Compute_Pos(pos);
467	            return;
468	        #elif (NUM_TARGETS_BUFFERS == 3)
469	            vec3 dummy_norm = vec3(0.0);
470	            vec3 dummy_tan = vec3(0.0);
471	            Morph_Compute_Pos_Norm_Tan(pos, dummy_norm, dummy_tan);
472	            return;
473	        #elif  (NUM_TARGETS_BUFFERS == 2)
474	            Morph_Compute_Pos_Norm(pos, norm);
475	        #endif
476	    }
477	
478	    void Morph_Compute(inout vec4 pos, inout vec3 norm, inout vec3 tan){
479	        #if (NUM_TARGETS_BUFFERS == 1)
480	            Morph_Compute_Pos(pos);
481	            return;
482	        #elif (NUM_TARGETS_BUFFERS == 2)
483	            Morph_Compute_Pos_Norm(pos, norm);
484	            tan = normalize(tan - dot(tan, norm) * norm);
485	            return;
486	        #elif (NUM_TARGETS_BUFFERS == 3)
487	            Morph_Compute_Pos_Norm_Tan(pos, norm, tan);
488	        #endif
489	    }
490	
491	#endif
492	// -- end import Common/ShaderLib/MorphAnim.glsllib --
493	
494	attribute vec3 inPosition;
495	
496	#if defined(HAS_COLORMAP) || (defined(HAS_LIGHTMAP) && !defined(SEPARATE_TEXCOORD))
497	    #define NEED_TEXCOORD1
498	#endif
499	
500	attribute vec2 inTexCoord;
501	attribute vec2 inTexCoord2;
502	attribute vec4 inColor;
503	
504	varying vec2 texCoord1;
505	varying vec2 texCoord2;
506	
507	varying vec4 vertColor;
508	#ifdef HAS_POINTSIZE
509	    uniform float m_PointSize;
510	#endif
511	
512	void main(){
513	    #ifdef NEED_TEXCOORD1
514	        texCoord1 = inTexCoord;
515	    #endif
516	
517	    #ifdef SEPARATE_TEXCOORD
518	        texCoord2 = inTexCoord2;
519	    #endif
520	
521	    #ifdef HAS_VERTEXCOLOR
522	        vertColor = inColor;
523	    #endif
524	
525	    #ifdef HAS_POINTSIZE
526	        gl_PointSize = m_PointSize;
527	    #endif
528	
529	    vec4 modelSpacePos = vec4(inPosition, 1.0);
530	
531	    #ifdef NUM_MORPH_TARGETS
532	        Morph_Compute(modelSpacePos);
533	    #endif
534	
535	    #ifdef NUM_BONES
536	        Skinning_Compute(modelSpacePos);
537	    #endif
538	
539	    gl_Position = TransformWorldViewProjection(modelSpacePos);
540	}

May 13, 2021 10:15:16 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.renderer.RendererException: compile error in: ShaderSource[name=Common/MatDefs/Misc/Unshaded.vert, defines, type=Vertex, language=GLSL150]
0:377(9): error: `m_MorphWeights' undeclared

	at com.jme3.renderer.opengl.GLRenderer.updateShaderSourceData(GLRenderer.java:1516)
	at com.jme3.renderer.opengl.GLRenderer.updateShaderData(GLRenderer.java:1543)
	at com.jme3.renderer.opengl.GLRenderer.setShader(GLRenderer.java:1608)
	at com.jme3.material.logic.DefaultTechniqueDefLogic.render(DefaultTechniqueDefLogic.java:96)
	at com.jme3.material.Technique.render(Technique.java:167)
	at com.jme3.material.Material.render(Material.java:1033)
	at com.jme3.renderer.RenderManager.renderGeometry(RenderManager.java:634)
	at com.jme3.renderer.queue.RenderQueue.renderGeometryList(RenderQueue.java:273)
	at com.jme3.renderer.queue.RenderQueue.renderQueue(RenderQueue.java:312)
	at com.jme3.renderer.RenderManager.renderViewPortQueues(RenderManager.java:897)
	at com.jme3.renderer.RenderManager.flushQueue(RenderManager.java:799)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1128)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1180)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:273)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:160)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:201)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:242)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Ali-RS** [comment]
Sorry, the issue was because I was using a modified version of MorphController in my fork.
