### ISSUE TITLE
Android application gets not shutdown completely

### ISSUE THREAD

**Issue by zzuegg** [jMonkeyEngine/jmonkeyengine#157]
When quiting the activity trough the dialog the application gets not shutdown completely. As it seems it is still holding a lock on some file, and then the following restart fails with a 

```
com.jme3.asset.AssetNotFoundException: Interface/Fonts/Default.fnt
            at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:283)
            at com.jme3.asset.DesktopAssetManager.loadFont(DesktopAssetManager.java:370)
            at com.jme3.app.SimpleApplication.loadGuiFont(SimpleApplication.java:179)
            at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:187)
            at com.jme3.app.AndroidHarness.initialize(AndroidHarness.java:455)
            at com.jme3.system.android.OGLESContext.initInThread(OGLESContext.java:229)
            at com.jme3.system.android.OGLESContext.onSurfaceCreated(OGLESContext.java:205)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1503)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1242)
```

A possible solution is to override the onDestroy() method with following code:

```
    @Override
    public void onDestroy() {
        super.onDestroy();
        System.runFinalization();
        android.os.Process.killProcess(android.os.Process.myPid());
    }
```

I guess the last two commands could also be added to the AndroidHarness.java and trough that fixing the issue for all users.

**Comment by shadowislord** [comment]
Closing due to no activity
