### ISSUE TITLE
cryptic crash caused by jme3-jogg library absent at runtime

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1604]
Raised at the Forum/Hub: https://hub.jmonkeyengine.org/t/why-this-exception-appears/44890

Surely we can provide a more helpful diagnostic!

How to reproduce the crash:

In "jme3-examples/build.gradle", replace
```groovy
implementation project(':jme3-jogg')
```
with
```groovy
compileOnly project(':jme3-jogg')
```
and then run one of the audio tests, such as "TestOgg".

Typical console output, for current "master" branch:
```text
Playing without filter
Sep 06, 2021 9:12:57 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,6,main]
com.jme3.asset.AssetLoadException: No loader registered for type "ogg"
	at com.jme3.asset.ImplHandler.aquireLoader(ImplHandler.java:196)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:268)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:388)
	at com.jme3.audio.AudioNode.<init>(AudioNode.java:164)
	at com.jme3.audio.AudioNode.<init>(AudioNode.java:144)
	at jme3test.audio.TestOgg.simpleInitApp(TestOgg.java:53)
```

**Comment by MeFisto94** [comment]
A piece in the puzzle is https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/resources/com/jme3/asset/Desktop.cfg:
It's registering a jogg loader as core, even when no ogg loader is present.
That being said, I don't think fixing that would make a difference though: The Asset Manager just skips loaders that it can't locate.

That means if we really want to configure that exception message, we'd need a `JoggLoaderWrapper` that is part of the core and delegates calls to jogg, if present, otherwise fails _nicely_.
However, I don't think it requires _too much_ cognitive energy to guess that a dependency that provides a loader may be missing, if no loader is registered.

We can append a `Do you miss a dependency?` or likewise to the exception message itself, if that is enough, then it'd be an easy fix.

**Comment by stephengold** [comment]
I had in mind something like this:
```java
        if (local == null) {
            String message = String.format(
                    "No loader registered for type \"%s\".",
                    key.getExtension());
            if (key.getExtension().equals("ogg")) {
                message += "  Probably the jme3-jogg library"
                        + " is missing from the runtime classpath.";
            }
            throw new AssetLoadException(message);
        }
```

**Comment by MeFisto94** [comment]
Well, if you want to do that correct, you'd probably need to add a lot of types, considering a lot of the things AWT loads are not there on mobile platforms, so you have similar issues when not adding `jme3-android-native` (not sure about iOS), or gltf/obj that come from jme3-plugins, etc.

So, in most occassions (unless missing an entry in the above cfg or manually unregistering a loader), this exception hints to a missing dependency of some sort

**Comment by pspeed42** [comment]
Yeah, I'm kind of against adding a special case for this one dependency.  Either add special cases for every conceivable dependency issue (I think not!) or just expand the message to suggest that maybe a dependency is missing.

But really we have to decide how much hand-holding we want to do.  On some level, the error is obvious and trivially answered just from the error message if the user doesn't know and asks the question.

I kind of feel like the "this plugin is not available because you didn't include the jar" thing is Java-universal.  And how far would we go with an extended error message?  Include instructions for several build tools?  Because the same logic as "Users don't understand what to do with 'loader not registered' messages" could also be applied to "users don't know what to do with 'dependency might be missing' messages".  They are going to have to seek help either way and the folks who can help will already know instantly 100% exactly what is wrong from the current message.
