### ISSUE TITLE
NullPointerException in TestIssue1120 when run from TestChooser

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1687]
When run from the test chooser, `TestIssue1120` in jme3-examples crashes:
```text
Nov 28, 2021 1:10:12 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,6,main]
java.lang.NullPointerException
	at jme3test.bullet.TestIssue1120.simpleInitApp(TestIssue1120.java:142)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:240)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:139)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:221)
	at java.lang.Thread.run(Thread.java:748)
```

The application's `test` field is `null` because it wasn't initialized. The initialization was placed in `main()`, which the test chooser never executes.

**Comment by bob0bob** [comment]
I submitted a pull request for this fix.
