### ISSUE TITLE
Attempt to Link in SceneComposer results in "NullPointerException"

### ISSUE THREAD

**Issue by stevenbright** [jMonkeyEngine/jmonkeyengine#1832]
Steps to reproduce:

1. Create a new scene based on "empty jME3 scene" template.
2. Hit "Edit in Scene Composer". It opens an empty view with coordination axis
3. Hit "File -> Link in Scene Composer"

Actual Result: NullPointerException thrown:

<img width="695" alt="Screen Shot 2022-07-02 at 4 19 05 PM" src="https://user-images.githubusercontent.com/983078/177018975-57bc2491-1b57-45f6-95f6-5fa888c5eab5.png">

Notes:

After step 1 I'm unable to open a scene. E.g. when I click on scene nothing happens, hence I try "Edit in Scene Composer"

My environment details as per jmonkey about window:

```
Product Version: jMonkeyEngine SDK v3.3.0-stable
Java: 11.0.6; OpenJDK 64-Bit Server VM 11.0.6+10
Runtime: OpenJDK Runtime Environment 11.0.6+10
System: Mac OS X version 10.16 running on x86_64; UTF-8; en_US (jmonkeyplatform)
```

Also I'm using openjdk11 that I installed via brew (`brew install openjdk@11`).

**Comment by stevenbright** [comment]
NullPointerException details:

<img width="695" alt="Screen Shot 2022-07-02 at 4 19 05 PM" src="https://user-images.githubusercontent.com/983078/177019026-6d232ee3-d403-41af-ad39-8d01ac8a2ae8.png">

**Comment by stevenbright** [comment]
Also when I open a project in the SDK's editor, I'm getting a similar error:

```
Loaded asset CookScene
java.lang.NullPointerException
	at com.jme3.gde.scenecomposer.SceneEditorController$17.run(SceneEditorController.java:721)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException
	at com.jme3.gde.scenecomposer.SceneEditorController$17.run(SceneEditorController.java:721)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by pspeed42** [comment]
Since this is an SDK bug and not an engine bug, you may want to report it in the jMonkeyEngine/sdk project.  https://github.com/jMonkeyEngine/sdk

**Comment by stevenbright** [comment]
Makes sense, thanks! Posted https://github.com/jMonkeyEngine/sdk/issues/350
