### ISSUE TITLE
TerrainGridTest throws AssetLoadException

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#1837]
Hi

Running jme3test.terrain.TerrainGridTest throws this error:

```
com.jme3.asset.AssetLoadException: Failed to open zip file: TerrainGridTestData.zip
	at com.jme3.asset.plugins.ZipLocator.setRootPath(ZipLocator.java:81)
	at com.jme3.asset.ImplHandler$ImplThreadLocal.initialValue(ImplHandler.java:120)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at com.jme3.asset.ImplHandler.tryLocate(ImplHandler.java:173)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:374)
	at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:407)
	at com.jme3.terrain.geomipmap.grid.ImageTileLoader.getHeightMapAt(ImageTileLoader.java:115)
	at com.jme3.terrain.geomipmap.grid.ImageTileLoader.getTerrainQuadAt(ImageTileLoader.java:159)
	at com.jme3.terrain.geomipmap.TerrainGrid$UpdateQuadCache.run(TerrainGrid.java:152)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: TerrainGridTestData.zip (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at com.jme3.asset.plugins.ZipLocator.setRootPath(ZipLocator.java:79)
	... 14 more
Caused by: java.io.FileNotFoundException: TerrainGridTestData.zip (No such file or directory)

```

Changing `assetManager.registerLocator("TerrainGridTestData.zip", ZipLocator.class);`
to `assetManager.registerLocator("./jme3-examples/TerrainGridTestData.zip", ZipLocator.class);` fixed it.

Should I submit a PR with the suggested change?

**Comment by Ali-RS** [comment]
Nevermind, it was an IDE problem. Sorry!
