### ISSUE TITLE
java.util.zip.ZipException in HttpZipLocator

### ISSUE THREAD

**Issue by icyboxs** [jMonkeyEngine/jmonkeyengine#1843]
```
assetManager.registerLocator(
                    "https://www.icyboxs.com/icyboxs/Lina.zip",
                    HttpZipLocator.class);

 Node  model =  (Node)assetManager.loadModel("Stand.gltf");
```

Fails with this error:

```
com.jme3.asset.AssetLoadException: An error occurred loading Stand.gltf
	at com.jme3.scene.plugins.gltf.GltfLoader.loadFromStream(GltfLoader.java:181)
	at com.jme3.scene.plugins.gltf.GltfLoader.load(GltfLoader.java:106)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:272)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:388)
	at net.jmecn.HelloArmature.model(HelloArmature.java:321)
	at net.jmecn.HelloArmature.initScene(HelloArmature.java:257)
	at net.jmecn.HelloArmature.simpleInitApp(HelloArmature.java:114)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:240)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:139)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:221)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.google.gson.JsonIOException: java.util.zip.ZipException: invalid distance too far back
	at com.google.gson.internal.Streams.parse(Streams.java:62)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.jme3.scene.plugins.gltf.GltfLoader.loadFromStream(GltfLoader.java:123)
	... 10 more
Caused by: java.util.zip.ZipException: invalid distance too far back
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
	at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1295)
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1333)
	at com.google.gson.stream.JsonReader.consumeNonExecutePrefix(JsonReader.java:1576)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:534)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.internal.Streams.parse(Streams.java:46)
	... 12 more
```

Link to the file: https://www.icyboxs.com/icyboxs/lina.zip

**Comment by Ali-RS** [comment]
Fixed in commit https://github.com/jMonkeyEngine/jmonkeyengine/commit/f0b7a96e64017dc7d386d1b7f6e86698e0d4780f.
