### ISSUE TITLE
missing LWJGL v2 natives

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1908]
(This is technically an issue with the "lwjgl2" repo, but since it affects JMonkeyEngine v3.6, I think we should track it here.)

Recent master builds of "jme3-lwjgl" reference the LWJGL v2.9.4 release, which works great for Linux but is missing natives for Windows. The resulting crash looks like this:
```console
> Task :jme3-examples:runSingle
Jan 12, 2023 5:32:23 PM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.6.0-SNAPSHOT
 * Branch: master
 * Git Hash: b0e6ce7
 * Build Date: 2023-01-12
Exception in thread "jME3 Main" java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path: C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\ProgramData\chocolatey\bin;C:\ProgramData\nvm;C:\Program Files\nodejs;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\sgold\AppData\Local\Microsoft\WindowsApps;C:\Users\sgold\AppData\Roaming\npm;;.
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:220)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Ali-RS** [comment]
@stephengold thanks for detecting and reporting this issue.
