### ISSUE TITLE
NullPointerException in MikktspaceTangentGenerator

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1909]
When a model containing a mesh without indices is passed to `MikktspaceTangentGenerator.generate()`:
```console
SEVERE: Caught unexpected throwable:
java.lang.NullPointerException: Cannot invoke "com.jme3.scene.mesh.IndexBuffer.get(int)" because "index" is null
	at com.jme3.util.mikktspace.MikkTSpaceImpl.getIndex(MikkTSpaceImpl.java:119)
	at com.jme3.util.mikktspace.MikkTSpaceImpl.getPosition(MikkTSpaceImpl.java:68)
	at com.jme3.util.mikktspace.MikktspaceTangentGenerator.getPosition(MikktspaceTangentGenerator.java:719)
	at com.jme3.util.mikktspace.MikktspaceTangentGenerator.generateSharedVerticesIndexList(MikktspaceTangentGenerator.java:279)
	at com.jme3.util.mikktspace.MikktspaceTangentGenerator.genTangSpace(MikktspaceTangentGenerator.java:164)
	at com.jme3.util.mikktspace.MikktspaceTangentGenerator.genTangSpaceDefault(MikktspaceTangentGenerator.java:126)
	at com.jme3.util.mikktspace.MikktspaceTangentGenerator.generate(MikktspaceTangentGenerator.java:118)
```

**Comment by Ali-RS** [comment]
>When a model containing a mesh without indices

Would a mesh without an index buffer still be rendered?

**Comment by zzuegg** [comment]
You can render any mesh without indicies. used that before gl3 as instancing replacemwnt

**Comment by pspeed42** [comment]
An index buffer is only needed when you want to share vertexes.  Otherwise it's a waste of space.

**Comment by stephengold** [comment]
Meshes in JME are incredibly flexible, which makes generalized editing of meshes incredibly difficult. I know there are many other cases that `MikktspaceTangentGenerator` currently can't handle; this is just the one that happened to bite me first.

From glancing at the code, the next bug that jumps out at me is that `MikktspaceTangentGenerator` assumes all meshes are in `Triangles` mode. Meshes in `Lines` or `Points` mode should simply be skipped, but perhaps solutions are needed for the `TriangleFan` and `TriangleStrip` modes.

**Comment by pspeed42** [comment]
I half-remember that JME has a utility class to treat Triangles, TriangleFan, and TriangleStrip the same and I believe the original tangent generator might have used it.  My memory says that the Mikkspace generator was ported from something else and so probably just cut-pasted code as directly as possible.

It's also possible I have no idea what I'm talking about.  Normally I look at the code before making such statements but I'm pressed for time and I didn't want to leave the memory unmentioned.

**Comment by stephengold** [comment]
I guess you're half-remembering `Mesh.getIndicesAsList()`, which is what I used in #1910 to solve this issue. You're correct that `getIndicesAsList()` handles `TriangleFan` and `TriangleStrip` modes correctly. However, the tangent generator assumes throughout that the vertices of a triangle appear sequentially in vertex buffers, so I think there's still work to do for those modes---and also for indexed meshes in general(!)

**Comment by Ali-RS** [comment]
Merging #1910 automatically closed this. Please feel free to reopen it if more action is required.
