### ISSUE TITLE
NPE when attempting to load v1.0 GLB format

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#2131]
jme-plugins loads model assets in the glTF v2.0 format, which comes in both JSON and binary forms. There's an older version of glTF (v1.0) that jme3-plugins doesn't handle.

If a JME application attempts to load a v1.0 model in JSON form (.gltf), a `SEVERE` diagnostic message is logged and an `AssetLoadException` is thrown:

```console
Oct 25, 2023 11:42:12 AM com.jme3.scene.plugins.gltf.GltfLoader loadFromStream
SEVERE: Gltf Loader doesn't support this gltf version: 1.0
com.jme3.asset.AssetLoadException: An error occurred loading 2CylinderEngine/glTF/2CylinderEngine.gltf
```
This is well and good.

However, if JME application attempts to load a v1.0 model in binary format (.glb), a `NullPointerException` is thrown and no other diagnostic information is produced (output generated by a jMonkeyEngine 3.7.0-SNAPSHOT of Git hash c9d10eb) :

```console
Oct 25, 2023 11:47:36 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.NullPointerException
	at java.base/java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:108)
	at com.jme3.scene.plugins.gltf.GlbLoader.load(GlbLoader.java:76)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:274)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:390)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:441)
	at com.github.stephengold.wrench.test.CompareLoaders.loadModel(CompareLoaders.java:815)
```

jme3-plugins should provide the same level of diagnostics for binary glTF assets as it does for JSON ones, namely a message explaining that v1.0 isn't supported.

**Comment by stephengold** [comment]
The root cause of the NPE is that `json` was set to `null` in line 56 and the stream contains no chunk of type 0x4E4F534A.
