### ISSUE TITLE
ClassCastException in Texture.setKey() which loading .obj file

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#2135]
I noticed a defect in MTLLoader while developing the MonkeyWrench library.

The test data is [Obj/Spider](https://github.com/assimp/assimp-mdb/tree/master/model-db/Obj/Spider) from Assimp's model database.

When I tried to load the model using jme3-core, I got a `ClassCastException`, so I added the following code to `OBJLoader.load(AssetInfo)`:

```java
        } catch (java.lang.ClassCastException e) {
            e.printStackTrace();
```

and obtained the following stack trace:

```java
Oct 28, 2023 12:14:50 AM com.jme3.scene.plugins.MTLLoader loadTexture
WARNING: Cannot locate Spider/.\wal67ar_small.jpg (Flipped) (Mipmapped) for material Spider/spider.mtl
java.lang.ClassCastException: class com.jme3.asset.AssetKey cannot be cast to class com.jme3.asset.TextureKey (com.jme3.asset.AssetKey and com.jme3.asset.TextureKey are in unnamed module of loader 'app')
	at com.jme3.texture.Texture.setKey(Texture.java:429)
	at com.jme3.scene.plugins.MTLLoader.loadTexture(MTLLoader.java:187)
	at com.jme3.scene.plugins.MTLLoader.readLine(MTLLoader.java:233)
	at com.jme3.scene.plugins.MTLLoader.load(MTLLoader.java:306)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:274)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:390)
	at com.jme3.scene.plugins.OBJLoader.loadMtlLib(OBJLoader.java:351)
	at com.jme3.scene.plugins.OBJLoader.readLine(OBJLoader.java:397)
	at com.jme3.scene.plugins.OBJLoader.load(OBJLoader.java:596)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:274)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:390)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:441)
	at com.github.stephengold.wrench.test.CompareLoaders.loadModel(CompareLoaders.java:828)
```

The exception message seems familiar, but I was unable to find it in the GitHub issues, so I'm opening a new one.

**Comment by pspeed42** [comment]
Were you not able to see the stack trace in the original exception without adding temporary code?  If so... that's a problem, too.  Exceptions without stack traces are not very useful.

**Comment by stephengold** [comment]
In order to see the stack trace, I had to add code. I agree that's an issue.

**Comment by stephengold** [comment]
Another downloadable OBJ file that has this issue:

https://open3dmodel.com/3d-models/modern-house-free-3d-model_5880.html
