### ISSUE TITLE
Assertion error when deleting native objects in the SDK

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#214]
Sometime, I have this exception in the SDK
java.lang.AssertionError
	at com.jme3.util.NativeObjectManager.deleteNativeObject(NativeObjectManager.java:140)
	at com.jme3.util.NativeObjectManager.deleteUnused(NativeObjectManager.java:188)
	at com.jme3.renderer.opengl.GLRenderer.postFrame(GLRenderer.java:853)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.runLoop(LwjglOffscreenBuffer.java:128)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.run(LwjglOffscreenBuffer.java:156)
[catch] at java.lang.Thread.run(Thread.java:745)

Can't reproduce it systematically though

**Comment by erlend-sh** [comment]
This issue was moved to jMonkeyEngine/sdk#8
