### ISSUE TITLE
WaterFilter Material parameter is not defined: causticsMap on method setCausticsTexture()

### ISSUE THREAD

**Issue by nickidebruyn** [jMonkeyEngine/jmonkeyengine#2164]
I found a bug on the WaterFilter class when one wants to setCausticsTexture() it sets the wrong parameter on the material.

java.lang.IllegalArgumentException: Material parameter is not defined: causticsMap
	at com.jme3.material.Material.checkSetParam(Material.java:474)
	at com.jme3.material.Material.setTextureParam(Material.java:543)
	at com.jme3.material.Material.setTexture(Material.java:617)
	at com.jme3.water.WaterFilter.setCausticsTexture(WaterFilter.java:1039)

**Comment by stephengold** [comment]
Good catch, @nickidebruyn !
Do you want to submit a pull request, or shall I?

**Comment by nickidebruyn** [comment]
You are welcome to submit a PR.
I currently don't have the jme src checked out.
Thanks @stephengold .
