### ISSUE TITLE
implement the KHR_mesh_quantization extension

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#2222]
Khronos has specified [an extension to glTF](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_mesh_quantization/README.md) for loading meshes with byte and/or short coordinates.

Currently, attempting to load such a model results in an exception:

```console
com.jme3.asset.AssetLoadException: An error occurred loading AnimatedMorphCube/glTF-Quantized/AnimatedMorphCube.gltf
	at com.jme3.scene.plugins.gltf.GltfLoader.loadFromStream(GltfLoader.java:181)
	at com.jme3.scene.plugins.gltf.GltfLoader.load(GltfLoader.java:107)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:274)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:390)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:441)
	at com.github.stephengold.wrench.test.CompareLoaders.loadModel(CompareLoaders.java:886)
	at com.github.stephengold.wrench.test.CompareLoaders.loadModel(CompareLoaders.java:841)
	at com.github.stephengold.wrench.test.CompareLoaders.onAction(CompareLoaders.java:496)
	at jme3utilities.ui.DefaultInputMode.onAction(DefaultInputMode.java:186)
	at com.jme3.input.InputManager.invokeActions(InputManager.java:174)
	at com.jme3.input.InputManager.onKeyEventQueued(InputManager.java:474)
	at com.jme3.input.InputManager.processQueue(InputManager.java:871)
	at com.jme3.input.InputManager.update(InputManager.java:923)
	at com.jme3.app.LegacyApplication.update(LegacyApplication.java:805)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:249)
	at com.jme3.system.lwjgl.LwjglWindow.runLoop(LwjglWindow.java:631)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:721)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassCastException: class java.nio.DirectShortBufferU cannot be cast to class java.nio.FloatBuffer (java.nio.DirectShortBufferU and java.nio.FloatBuffer are in module java.base of loader 'bootstrap')
	at com.jme3.scene.plugins.gltf.GltfLoader.readMeshPrimitives(GltfLoader.java:457)
	at com.jme3.scene.plugins.gltf.GltfLoader.readNode(GltfLoader.java:252)
	at com.jme3.scene.plugins.gltf.GltfLoader.readChild(GltfLoader.java:301)
	at com.jme3.scene.plugins.gltf.GltfLoader.readChild(GltfLoader.java:309)
	at com.jme3.scene.plugins.gltf.GltfLoader.readScenes(GltfLoader.java:218)
	at com.jme3.scene.plugins.gltf.GltfLoader.loadFromStream(GltfLoader.java:155)
	... 17 more
```

Since the extension may be widely used in the future, it would be nice if jme3-plugins could handle it. I haven't scoped out the changes and don't know whether the core engine supports such meshes.

For examples, see [the glTF-Sample-Assets repo at GitHub](https://github.com/KhronosGroup/glTF-Sample-Assets).

**Comment by stephengold** [comment]
I don't intend to work on this issue for at least a month. If someone wants to pursue the bounty, there's no need to wait!

**Comment by hunterbastian** [comment]
I would like to work on this bounty.

I have a local implementation ready for `KHR_mesh_quantization` support. It registers the extension, expands quantized mesh attributes to float buffers where needed, preserves index buffer formats, and adds a focused glTF loader test fixture for a required `KHR_mesh_quantization` asset.

Local verification is passing:

```text
./gradlew :jme3-plugins:test --tests com.jme3.scene.plugins.gltf.GltfLoaderTest --no-daemon
git diff --check
```

If assigned, I can open the PR from the prepared branch.

**Comment by hunterbastian** [comment]
Checking in on assignment for this bounty.

The prepared `KHR_mesh_quantization` branch is still ready, with the focused glTF loader test as the verification target. If assignment is approved, I can open the PR from that branch.

**Comment by stephengold** [comment]
@riccardobl Who approves bounty assignment?

**Comment by riccardobl** [comment]
> Checking in on assignment for this bounty.
> 
> The prepared `KHR_mesh_quantization` branch is still ready, with the focused glTF loader test as the verification target. If assignment is approved, I can open the PR from that branch.


please check my answer to the other issue : https://github.com/jMonkeyEngine/jmonkeyengine/issues/2354#issuecomment-4476439908

requirements are the same for all the bounties
