### ISSUE TITLE
Unclear exception info on invalid file path in asset locator

### ISSUE THREAD

**Issue by codex128** [jMonkeyEngine/jmonkeyengine#2230]
If an asset locator is registered with a nonexistent file path and then the system tries to locate an asset with it, a very unclear warning occurs followed by a null pointer exception.

```java
assetManager.registerLocator("NonExistentFolder", FileLocator.class);
assetManager.loadModel("NonExistentModel.j3o");
```
```stacktrace
SEVERE: Cannot create locator of type com.jme3.asset.plugins.FileLocator, does the class have an empty and publicly accessible constructor?
Mar 20, 2024 9:14:45 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.NullPointerException: Cannot invoke "com.jme3.asset.AssetLocator.locate(com.jme3.asset.AssetManager, com.jme3.asset.AssetKey)" because the return value of "com.jme3.asset.ImplHandler$ImplThreadLocal.get()" is null
	at com.jme3.asset.ImplHandler.tryLocate(ImplHandler.java:176)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:376)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:441)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:446)
	at mygame.GeneralTests.simpleInitApp(GeneralTests.java:24)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:240)
	at com.jme3.system.lwjgl.LwjglWindow.initInThread(LwjglWindow.java:610)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:714)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

The warning/exception should instead indicate that a nonexistent path is being used. I am working on a PR to fix this.

**Comment by codex128** [comment]
On closer inspection, the necessary information is logged, but on the FINER level. I think this should be changed to SEVERE, since a failure here results in a null pointer later.

https://github.com/jMonkeyEngine/jmonkeyengine/blob/8a71dce372dc7427e8b317ba0f86602e4836ef56/jme3-core/src/main/java/com/jme3/asset/ImplHandler.java#L130
