### ISSUE TITLE
TestSafeCanvas crash on launch

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#233]
TestSafeCAnvas fails with that exception

org.lwjgl.LWJGLException: Parent.isDisplayable() must be true
	at org.lwjgl.opengl.Display.createWindow(Display.java:301)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at com.jme3.system.lwjgl.LwjglDisplay.createContext(LwjglDisplay.java:142)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:114)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:210)
	at java.lang.Thread.run(Thread.java:745)
GRAVE LwjglAbstractDisplay 22:41:58 Display initialization failed. Cannot continue.

**Comment by Nehon** [comment]
Was actually an Issue due to previous issur with TestCanvas
