### ISSUE TITLE
TestHoveringTank throws an assertion error

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#234]
Launch TestHoveringTank and shoot rockets (space bar). At some point you get an assertion error
java.lang.AssertionError
    at com.jme3.bounding.BoundingSphere.intersectsBoundingBox(BoundingSphere.java:691)
    at com.jme3.bounding.BoundingBox.intersects(BoundingBox.java:587)
    at com.jme3.shadow.ShadowUtil$OccludersExtractor.process(ShadowUtil.java:428)
    at com.jme3.shadow.ShadowUtil$OccludersExtractor.addOccluders(ShadowUtil.java:368)
    at com.jme3.shadow.ShadowUtil.updateShadowCamera(ShadowUtil.java:501)
    at com.jme3.shadow.PssmShadowRenderer.postQueue(PssmShadowRenderer.java:436)
    at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1025)
    at com.jme3.renderer.RenderManager.render(RenderManager.java:1078)
    at com.jme3.app.SimpleApplication.update(SimpleApplication.java:260)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:152)
    at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:192)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:231)
    at java.lang.Thread.run(Thread.java:745)

**Comment by shadowislord** [comment]
Seems to be fixed since the code avoids passing invalid vectors to the collision function
