### ISSUE TITLE
TestQ3 fails with a fileNotFound exception

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#235]
TestQ3 : 
com.jme3.asset.AssetLoadException: Failed to open zip file: quake3level.zip
	at com.jme3.asset.plugins.ZipLocator.setRootPath(ZipLocator.java:79)
	at com.jme3.asset.ImplHandler.tryLocate(ImplHandler.java:175)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:363)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:390)
	at jme3test.bullet.TestQ3.simpleInitApp(TestQ3.java:98)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:227)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:131)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:210)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: quake3level.zip (Le fichier spécifié est introuvable)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
	at com.jme3.asset.plugins.ZipLocator.setRootPath(ZipLocator.java:77)
	... 8 more

**Comment by Nehon** [comment]
Actually, That's because the TestChooser doesn't launch the main()...which is dumb
