### ISSUE TITLE
TestAssetLinkNode is freezing at start

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#238]
Title says everything

**Comment by stephengold** [comment]
Current `master` branch yields an exception and stack trace:
```
Dec 15, 2018 10:49:22 PM com.jme3.scene.plugins.ogre.MeshLoader load
WARNING: Cannot locate Models/MonkeyHead/MonkeyHead.material for model Models/MonkeyHead/MonkeyHead.mesh.xml
Dec 15, 2018 10:49:22 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.asset.AssetLoadException: An exception has occured while loading asset: Common/Materials/RedColor.j3m
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:261)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at jme3test.export.TestAssetLinkNode.simpleInitApp(TestAssetLinkNode.java:96)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Material instances must be loaded via MaterialKey
	at com.jme3.material.plugins.J3MLoader.load(J3MLoader.java:797)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	... 6 more
```
