### ISSUE TITLE
TestBlenderObjectAnim fails with a NPE

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#240]
java.lang.NullPointerException
    at jme3test.model.anim.TestBlenderObjectAnim.simpleInitApp(TestBlenderObjectAnim.java:76)
    at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:227)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:131)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:210)
    at java.lang.Thread.run(Thread.java:745)

**Comment by stephengold** [comment]
Still broken in current `master` (jMonkeyEngine 3.3-6666).

In the imported model, the `Node` with the `AnimControl` is actually named `"Cube"` not `"TestAnim"` and the animations are actually named `"Action"` and `"Action.001"` not `"TestAnim"`. Both errors can easily be corrected.

**Comment by stephengold** [comment]
Fixed in `master`.

**Comment by stephengold** [comment]
See also https://github.com/jMonkeyEngine/sdk/issues/96
