### ISSUE TITLE
TestNiftyExample crashes on start

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#241]
With this exception 
java.lang.RuntimeException: com.jme3.asset.AssetNotFoundException: all/intro.xml
	at de.lessvoid.nifty.Nifty.loadFromFile(Nifty.java:658)
	at de.lessvoid.nifty.Nifty.fromXml(Nifty.java:515)
	at jme3test.niftygui.TestNiftyExamples.simpleInitApp(TestNiftyExamples.java:56)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:227)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:131)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:210)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.jme3.asset.AssetNotFoundException: all/intro.xml
	at com.jme3.niftygui.NiftyJmeDisplay$ResourceLocationJme.getResourceAsStream(NiftyJmeDisplay.java:83)
	at de.lessvoid.nifty.tools.resourceloader.NiftyResourceLoader.getResourceAsStream(NiftyResourceLoader.java:69)
	at de.lessvoid.nifty.Nifty.getResourceAsStream(Nifty.java:1997)
	at de.lessvoid.nifty.Nifty.loadFromFile(Nifty.java:646)
	... 6 more

**Comment by Nehon** [comment]
Same issue for NiftyToMesh
