### ISSUE TITLE
TestMultipleFilters crashes on start

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#242]
With this exception
com.jme3.asset.AssetLoadException: Failed to open zip file: wildhouse.zip
	at com.jme3.asset.plugins.ZipLocator.setRootPath(ZipLocator.java:79)
	at com.jme3.asset.ImplHandler.tryLocate(ImplHandler.java:175)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:363)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:420)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:424)
	at jme3test.post.TestMultiplesFilters.simpleInitApp(TestMultiplesFilters.java:84)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:227)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:131)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:210)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: wildhouse.zip (Le fichier spécifié est introuvable)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
	at com.jme3.asset.plugins.ZipLocator.setRootPath(ZipLocator.java:77)
	... 9 more

**Comment by Nehon** [comment]
SAme for TestPostFiltersCompositing

**Comment by Nehon** [comment]
Same issue as issue #235 TestChooser doesn't run the main() which init the http settings to get the zip file through an httpLocator
