### ISSUE TITLE
TestTExtureArray fails with invalid Enum

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#243]
org.lwjgl.opengl.OpenGLException: Invalid enum (1280)
	at org.lwjgl.opengl.Util.checkGLError(Util.java:59)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.checkGLError(LwjglAbstractDisplay.java:137)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:158)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:192)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:231)
	at java.lang.Thread.run(Thread.java:745)

**Comment by shadowislord** [comment]
Unable to reproduce. Run app with these settings:
```
TestTextureArray app = new TestTextureArray();
AppSettings settings = new AppSettings(true);
settings.putBoolean("GraphicsDebug", true);
app.setSettings(settings);
app.start();
```

**Comment by Nehon** [comment]
I'll test tonight thanks.

**Comment by Nehon** [comment]
Here is the complete error 
[LWJGL] ARB_debug_output message
	ID: 1280
	Source: API
	Type: ERROR
	Severity: HIGH
	Message: GL_INVALID_ENUM error generated. <cap> enum is invalid; expected GL_ALPHA_TEST, GL_BLEND, GL_COLOR_MATERIAL, GL_CULL_FACE, GL_DEPTH_TEST, GL_DITHER, GL_FOG, etc. (136 others).
mars 18, 2015 10:15:47 PM com.jme3.app.Application handleError
GRAVE: Uncaught exception thrown in Thread[LWJGL Renderer Thread,5,main]
com.jme3.renderer.RendererException: An OpenGL error occurred - Invalid enum argument (Error Code: 1280)
	at com.jme3.renderer.opengl.GLDebug.checkError(GLDebug.java:46)
	at com.jme3.renderer.opengl.GLDebugES.glEnable(GLDebugES.java:185)
	at com.jme3.renderer.opengl.GLRenderer.updateTexImageData(GLRenderer.java:2092)
	at com.jme3.renderer.opengl.GLRenderer.setTexture(GLRenderer.java:2108)
	at com.jme3.material.MatParamTexture.apply(MatParamTexture.java:112)
	at com.jme3.material.Material.render(Material.java:1177)
	at com.jme3.renderer.RenderManager.renderGeometry(RenderManager.java:568)
	at com.jme3.renderer.queue.RenderQueue.renderGeometryList(RenderQueue.java:266)
	at com.jme3.renderer.queue.RenderQueue.renderQueue(RenderQueue.java:305)
	at com.jme3.renderer.RenderManager.renderViewPortQueues(RenderManager.java:803)
	at com.jme3.renderer.RenderManager.flushQueue(RenderManager.java:731)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1030)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1078)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:260)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:152)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:192)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:231)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Nehon** [comment]
Fixed https://github.com/jMonkeyEngine/jmonkeyengine/commit/080255f51860d6803b88c0c91206a0c6c42da5f4
