### ISSUE TITLE
TestJoystick throws an assertion error when assertion are enabled

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#284]
When assertions are enabled on the test project TestJoystick throws this assertion error
```
java.lang.AssertionError
	at com.jme3.input.controls.JoyAxisTrigger.joyAxisHash(JoyAxisTrigger.java:52)
	at com.jme3.input.controls.JoyAxisTrigger.triggerHashCode(JoyAxisTrigger.java:73)
	at com.jme3.input.InputManager.addMapping(InputManager.java:561)
	at com.jme3.input.DefaultJoystickAxis.assignAxis(DefaultJoystickAxis.java:75)
	at com.jme3.input.FlyByCamera.mapJoystick(FlyByCamera.java:272)
	at com.jme3.input.FlyByCamera.registerWithInput(FlyByCamera.java:245)
	at com.jme3.app.FlyCamAppState.initialize(FlyCamAppState.java:75)
	at com.jme3.app.state.AppStateManager.initializePending(AppStateManager.java:251)
	at com.jme3.app.state.AppStateManager.update(AppStateManager.java:281)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:243)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:152)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:192)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:233)
	at java.lang.Thread.run(Thread.java:745)
```
seems that the culprit is this line
```
  assert joyAxis >= 0 && joyAxis <= 255;
```
in JoyAxisTrigger.joyAxisHash. joyAxis is sometimes equals to -1.
This issue was found with  FF14 joystick, idk if others also thow the error.
Note that when assertion are disabled it works wonderfully.

**Comment by pspeed42** [comment]
I wonder if the assertion is just bogus now, then.  I guess we'd have to look and see if some other thing has a problem with a negative joyAxis or if it's supposed to mean something else.  I also wonder where the joyAxis comes from (having not looked at the code in a while :))

Not sure when I will get to this.

**Comment by Nehon** [comment]
I'll look into it and poke you on the core chat about it if I have some questions ;)

**Comment by Nehon** [comment]
Fixed
