### ISSUE TITLE
Unclear error in BIHTree

### ISSUE THREAD

**Issue by noncom** [jMonkeyEngine/jmonkeyengine#291]
On [this line](https://github.com/jMonkeyEngine/jmonkeyengine/blob/e2d8fe829359dd6028d6810efddbf671d9980231/jme3-core/src/main/java/com/jme3/collision/bih/BIHTree.java#L117)  in BIHTree.java if the mesh does not have the `Position` buffer set up, the error is

    java.lang.NullPointerException
	at com.jme3.collision.bih.BIHTree.<init>(BIHTree.java:117)
	at com.jme3.collision.bih.BIHTree.<init>(BIHTree.java:130)
	at com.jme3.scene.Mesh.createCollisionData(Mesh.java:885)
	at com.jme3.scene.Mesh.collideWith(Mesh.java:905)
	at com.jme3.scene.Geometry.collideWith(Geometry.java:408)
	at com.jme3.scene.Node.collideWith(Node.java:494)
	at com.simsilica.lemur.event.PickEventSession.cursorMoved(PickEventSession.java:367)
	at com.simsilica.lemur.event.MouseAppState.update(MouseAppState.java:171)
	at com.jme3.app.state.AppStateManager.update(AppStateManager.java:287)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:239)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:185)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:228)
	at java.lang.Thread.run(Unknown Source)

If a mesh is forced to have the Position buffer to be valid, won't a more clear message here or somewhere else suggest that prior coming to this NPE in runtime? The stack trace which is strictly within the bounds of the platform itself looks like it is an unexpected situation, and probably a bug..?

**Comment by afonsolage** [comment]
But by adding those kind of checks, will slow down the performance...Since JME3 is focused on performance rather than trivial checks, I think this isn't much necessary.

**Comment by Nehon** [comment]
Also a mesh without position buffer is really unexpected

**Comment by noncom** [comment]
Aaaaalright :) then I think this issue is not an issue and can be closed?

**Comment by Nehon** [comment]
Ok we talked about it in the core chat an decided to add a check, it's been fixed on master.
