### ISSUE TITLE
Exception thrown when jME application is executed from SMB share

### ISSUE THREAD

**Issue by shadowislord** [jMonkeyEngine/jmonkeyengine#317]
```
java.lang.IllegalArgumentException: URI has an authority component
    at java.io.File.(File.java:423)
    at com.jme3.asset.plugins.ClasspathLocator.locate(ClasspathLocator.java:88)
```

When running from a path like `\\abc\def\`, jME3 crashes in `ClasspathLoader`:
at  `String path = new File(url.toURI()).getCanonicalPath();`

Creating a File object from an SMB path isn't supported by Java (?)

**Comment by empirephoenix** [comment]
No, it does not but it is a rather strange usecase, especially since mounting/ net-drive solves it.
In fact the reason is that the underlying API does not support this on both windows and Linux. 

At least on Linux those cases are usually handled via file manger that just mounts it via fuse or natively can connect to it. In the later case all started applications need to support the networking protocols as well.

**Comment by shadowislord** [comment]
I don't think Windows users would care about how it works on Linux. 

The point is that a jME application executed from an SMB share crashes on boot, that's generally not a good thing regardless. A user may not wish to mount a net-drive, they may wish to run it directly from the SMB share.

**Comment by empirephoenix** [comment]
Well we could just add a simple catch for that exact case and a message that running the sdk from a share is not supported. I see this often under windows, for example the Microsoft installer system itself cannot do this.
