### ISSUE TITLE
Texture.WrapMode.MirrorBorderClamp throws UnsupportedOperationException

### ISSUE THREAD

**Issue by redboffin** [jMonkeyEngine/jmonkeyengine#389]
I'm using JME3 on Windows 10. I was trying out the different modes to see what they did and this one throws the exception.

Dec 11, 2015 11:07:22 PM com.jme3.app.Application handleError
SEVERE: Uncaught exception thrown in Thread[LWJGL Renderer Thread,5,main]
java.lang.UnsupportedOperationException: Unknown wrap mode: MirrorBorderClamp
	at com.jme3.renderer.lwjgl.LwjglRenderer.convertWrapMode(LwjglRenderer.java:1737)
	at com.jme3.renderer.lwjgl.LwjglRenderer.setupTextureParams(LwjglRenderer.java:1772)
	at com.jme3.renderer.lwjgl.LwjglRenderer.setTexture(LwjglRenderer.java:1966)
	at com.jme3.material.MatParamTexture.apply(MatParamTexture.java:86)
	at com.jme3.material.Material.render(Material.java:1088)
	at com.jme3.renderer.RenderManager.renderGeometry(RenderManager.java:523)
	at com.jme3.renderer.queue.RenderQueue.renderGeometryList(RenderQueue.java:322)
	at com.jme3.renderer.queue.RenderQueue.renderQueue(RenderQueue.java:374)
	at com.jme3.renderer.RenderManager.renderViewPortQueues(RenderManager.java:763)
	at com.jme3.renderer.RenderManager.flushQueue(RenderManager.java:719)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:983)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1029)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:252)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:185)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:228)
	at java.lang.Thread.run(Thread.java:744)

**Comment by DannyJo** [comment]
Well, the simple answer is that the LwjglRenderer in 3.0.10 does not support using that wrap mode on a texture.

Extended answer is that in 3.1 WrapMode.MirrorBorderClamp and most others are deprecated so you should no longer be using it.

For supported modes in 3.0.10 see this link.
https://github.com/jMonkeyEngine/jmonkeyengine/blob/3.0/engine/src/lwjgl/com/jme3/renderer/lwjgl/LwjglRenderer.java#L1724
