### ISSUE TITLE
The new J3MExporter NPEs on null values

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/jmonkeyengine#453]
The new J3MExporter NPEs on null values. The forums are down so no discussion beforehand, but I'm pretty sure this is a bug. My material has "additionalState" as null. com.jme3.material.Material.java:1237 tries to write it.

NPE here:
https://github.com/jMonkeyEngine/jmonkeyengine/blob/v3.1.0-alpha3/jme3-plugins/src/main/java/com/jme3/material/plugin/export/material/J3MRootOutputCapsule.java#L94

**Comment by tonihele** [comment]
I think you can just workaround this by calling getAdditionalRenderState() on the material once, it'll create an empty one.

**Comment by Nehon** [comment]
Sounds like a bug, but it would help to have the complete stacktrace and/or a test case.

**Comment by tonihele** [comment]
Stack:

```
SEVERE: Failed to convert the assets!
java.lang.RuntimeException: Failed to convert KMF entry g_Maiden-Torture.kmf!
	at toniarts.openkeeper.tools.convert.AssetsConverter.convertModel(AssetsConverter.java:399)
	at toniarts.openkeeper.tools.convert.AssetsConverter.convertModels(AssetsConverter.java:337)
	at toniarts.openkeeper.tools.convert.AssetsConverter.convertAssets(AssetsConverter.java:206)
	at toniarts.openkeeper.setup.DKConverter$Converter.run(DKConverter.java:251)
Caused by: java.lang.NullPointerException
	at com.jme3.material.plugin.export.material.J3MRootOutputCapsule.write(J3MRootOutputCapsule.java:94)
	at com.jme3.material.Material.write(Material.java:1237)
	at com.jme3.material.plugin.export.material.J3MExporter.save(J3MExporter.java:56)
	at com.jme3.material.plugin.export.material.J3MExporter.save(J3MExporter.java:65)
	at toniarts.openkeeper.tools.convert.KmfModelLoader.getMaterials(KmfModelLoader.java:779)
	at toniarts.openkeeper.tools.convert.KmfModelLoader.load(KmfModelLoader.java:156)
	at toniarts.openkeeper.tools.convert.AssetsConverter.convertModel(AssetsConverter.java:390)
	... 3 more

Mar 17, 2016 1:50:43 PM toniarts.openkeeper.Main main
```

**Comment by tonihele** [comment]
I think this is quite simple to test, just create a new material without touching the additional render states and try to use the exporter to save it. Should fail immediately. By default I don't think the materials have additional render states set.

**Comment by Nehon** [comment]
yep got it

**Comment by Nehon** [comment]
fixed, thanks.
https://github.com/jMonkeyEngine/jmonkeyengine/commit/107123820bed1fd215566d3e3edad7cb84e1d304

**Comment by tonihele** [comment]
Thanks!
