### ISSUE TITLE
Cloning NPE

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#466]
This happens when trying to load a terrain:

```
java.lang.NullPointerException
	at com.jme3.util.clone.Cloner.javaClone(Cloner.java:357)
	at com.jme3.terrain.geomipmap.TerrainLodControl.cloneFields(TerrainLodControl.java:323)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:255)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.util.clone.ListCloneFunction.cloneFields(ListCloneFunction.java:66)
	at com.jme3.util.clone.ListCloneFunction.cloneFields(ListCloneFunction.java:43)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:228)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.scene.Spatial.cloneFields(Spatial.java:1422)
	at com.jme3.scene.Node.cloneFields(Node.java:726)
	at com.jme3.terrain.geomipmap.TerrainQuad.cloneFields(TerrainQuad.java:1816)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:255)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.util.clone.ListCloneFunction.cloneFields(ListCloneFunction.java:66)
	at com.jme3.util.clone.ListCloneFunction.cloneFields(ListCloneFunction.java:43)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:228)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.scene.Node.cloneFields(Node.java:728)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:255)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.scene.Spatial.clone(Spatial.java:1289)
	at com.jme3.scene.Node.clone(Node.java:684)
	at com.jme3.scene.Node.clone(Node.java:62)
	at com.jme3.scene.Spatial.clone(Spatial.java:1368)
	at com.jme3.scene.Spatial.clone(Spatial.java:69)
	at com.jme3.asset.CloneableAssetProcessor.createClone(CloneableAssetProcessor.java:48)
	at com.jme3.asset.DesktopAssetManager.registerAndCloneSmartAsset(DesktopAssetManager.java:320)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:382)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:419)
[catch] at com.jme3.gde.core.assets.SpatialAssetDataObject.loadAsset(SpatialAssetDataObject.java:95)
	at com.jme3.gde.scenecomposer.OpenSceneComposer$1.run(OpenSceneComposer.java:37)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pspeed42** [comment]
This bug is already fixed in 'master'.  A user reported it on the forum the day after alpha 4 was released and I fixed it the same day.

**Comment by pspeed42** [comment]
For reference: https://hub.jmonkeyengine.org/t/npe-with-jmonkeyengine-3-1-alpha-4-in-terrainlodcontrol/35484

**Comment by MeFisto94** [comment]
Oh, apologies.
I should've searched for that issue before posting it.

**Comment by pspeed42** [comment]
Nah, it's good to have it here, too...as this is where people would likely
look for existing bugs.
