### ISSUE TITLE
Exception For No Apparent Reason

### ISSUE THREAD

**Issue by john01dav** [jMonkeyEngine/jmonkeyengine#474]
I was recently testing my game and the following crash happened without apparent cause as a significant number of procedural geometries were attached:

```
java.lang.IllegalArgumentException: This NativeObject is not registered in this NativeObjectManager
	at com.jme3.util.NativeObjectManager.deleteNativeObject(NativeObjectManager.java:136)
	at com.jme3.util.NativeObjectManager.deleteUnused(NativeObjectManager.java:188)
	at com.jme3.renderer.opengl.GLRenderer.postFrame(GLRenderer.java:870)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:189)
	at com.jme3.system.lwjgl.LwjglCanvas.runLoop(LwjglCanvas.java:229)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:745)
```

In the past, when the exact same geometries (generated from the same seed) were attached, this issue didn't occur. It also does not occur if I load those same geometries again.

**Comment by pspeed42** [comment]
You should post trouble shooting questions to the forum.  Most likely cause
for stuff like this is threading issues.

**Comment by john01dav** [comment]
I assumed that it is a JME bug since non of my packages are involved in the stack trace. I'll post it to the form anyway though.
