### ISSUE TITLE
Lighting.j3md with PBR, "LightSpace" test fail

### ISSUE THREAD

**Issue by phr00t** [jMonkeyEngine/jmonkeyengine#476]
I get the following error in many places, but it seems to be the same error. This is using the latest commits from both PBR & master branches as of this issue submission. Is this something I need to fix in my branch merge, or is this something related to PBR not being updated yet..? @Nehon ?

:jme3-core:test

com.jme3.material.MaterialMatParamOverrideTest > testMpoDisable FAILED
    com.jme3.asset.AssetLoadException: An exception has occured while loading asset: Common/MatDefs/Light/Lighting.j3md
        at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:261)
        at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
        at com.jme3.material.Material.<init>(Material.java:118)
        at com.jme3.material.MaterialMatParamOverrideTest.material(MaterialMatParamOverrideTest.java:494)
        at com.jme3.material.MaterialMatParamOverrideTest.testMpoDisable(MaterialMatParamOverrideTest.java:159)

```
    Caused by:
    com.jme3.material.plugins.MatParseException: Error On line 122 : LightSpace View
    ->Expected a statement, got 'LightSpace'!
        at com.jme3.material.plugins.J3MLoader.readTechniqueStatement(J3MLoader.java:574)
        at com.jme3.material.plugins.J3MLoader.readTechnique(J3MLoader.java:612)
        at com.jme3.material.plugins.J3MLoader.loadFromRoot(J3MLoader.java:734)
        at com.jme3.material.plugins.J3MLoader.load(J3MLoader.java:755)
        at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
        ... 4 more
```

**Comment by shadowislord** [comment]
The unit tests are passing for me, cannot reproduce
