### ISSUE TITLE
Cannot disable audio renderer in 3.1.0 alpha 5

### ISSUE THREAD

**Issue by jupake** [jMonkeyEngine/jmonkeyengine#479]
When I call 

```java
settings.setAudioRenderer(null);
```

I get the following error when I try to run the application. 

```
Apr 21, 2016 2:51:33 PM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.1-alpha5
 * Branch: HEAD
 * Git Hash: 8d4962d
 * Build Date: 2016-04-11
Apr 21, 2016 2:51:33 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: null
 * Driver Version: null
 * Scaling Factor: 1
Apr 21, 2016 2:51:33 PM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
 * Vendor: NVIDIA Corporation
 * Renderer: GeForce GTX 970M/PCIe/SSE2
 * OpenGL Version: 4.5.0 NVIDIA 352.63
 * GLSL Version: 4.50 NVIDIA
 * Profile: Compatibility
Apr 21, 2016 2:51:33 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.ogre.MeshLoader
Apr 21, 2016 2:51:33 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.ogre.SkeletonLoader
Apr 21, 2016 2:51:33 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.ogre.MaterialLoader
Apr 21, 2016 2:51:33 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.ogre.SceneLoader
Apr 21, 2016 2:51:33 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.blender.BlenderModelLoader
Apr 21, 2016 2:51:33 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.fbx.FbxLoader
Apr 21, 2016 2:51:33 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.audio.plugins.OGGLoader
Apr 21, 2016 2:51:33 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.NullPointerException
	at com.jme3.audio.AudioListenerState.render(AudioListenerState.java:77)
	at com.jme3.app.state.AppStateManager.render(AppStateManager.java:300)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:250)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:745)
```
I looks like its not checking for null in the AudioListenerState.

**Comment by pspeed42** [comment]
Even better, the AudioListenerState should maybe not even be added if there is no audio renderer configured.  But yeah, at least it should check for null.
