### ISSUE TITLE
Incomplete draw buffer error on AMD cards

### ISSUE THREAD

**Issue by jojoofu** [jMonkeyEngine/jmonkeyengine#558]
This only happens on AMD cards. Two specifically that cause it are the hd6410/5850. I deconverted my project back to 3.0 and it ran fine on both cards. The issue only seems to be present in 3.1

java.lang.IllegalStateException: Incomplete draw buffer.
at com.jme3.renderer.opengl.GLRenderer.checkFrameBufferError(GLRenderer.java:1425)
at com.jme3.renderer.opengl.GLRenderer.updateFrameBuffer(GLRenderer.java:1590)
at com.jme3.renderer.opengl.GLRenderer.setFrameBuffer(GLRenderer.java:1736)
at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1072)
at com.jme3.renderer.RenderManager.render(RenderManager.java:1145)
at com.jme3.app.SimpleApplication.update(SimpleApplication.java:253)
at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
at java.lang.Thread.run(Thread.java:745)

**Comment by shadowislord** [comment]
Log from forum post:
```
Sep 19, 2016 10:49:23 PM java.util.prefs.WindowsPreferences
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Sep 19, 2016 10:49:31 PM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.1-beta1
* Branch: HEAD
* Git Hash: 310f4db
* Build Date: 2016-04-25
Sep 19, 2016 10:49:32 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 2.9.3 context running on thread jME3 Main
* Graphics Adapter: aticfx64
* Driver Version: 8.17.10.1094
* Scaling Factor: 1
Sep 19, 2016 10:49:33 PM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
* Vendor: ATI Technologies Inc.
* Renderer: AMD RADEON HD6410D Graphics
* OpenGL Version: 4.1.11079 Compatibility Profile/Debug Context
* GLSL Version: 4.10
* Profile: Core
Sep 19, 2016 10:49:33 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.blender.BlenderModelLoader
Sep 19, 2016 10:49:33 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio Renderer Information
* Device: OpenAL Soft
* Vendor: OpenAL Community
* Renderer: OpenAL Soft
* Version: 1.1 ALSOFT 1.15.1
* Supported channels: 64
* ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
* AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
Sep 19, 2016 10:49:33 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
Sep 19, 2016 10:49:33 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio effect extension version: 1.0
Sep 19, 2016 10:49:33 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio max auxiliary sends: 4
Bullet-Native: Initializing java classes
Sep 19, 2016 10:49:34 PM com.jme3.texture.Texture read
SEVERE: Cannot locate texture loading.png (Flipped) (Mipmapped)
Sep 19, 2016 10:49:34 PM com.jme3.texture.Texture read
SEVERE: Cannot locate texture dot.png (Flipped) (Mipmapped)
Sep 19, 2016 10:49:34 PM com.jme3.texture.Texture read
SEVERE: Cannot locate texture dot.png (Flipped) (Mipmapped)
Sep 19, 2016 10:49:34 PM com.jme3.texture.Texture read
SEVERE: Cannot locate texture dot.png (Flipped) (Mipmapped)
Sep 19, 2016 10:49:36 PM com.jme3.material.Material setTextureParam
WARNING: The texture Models/zombiecommon/textures/zombie_common_hood.tga has linear color space, but the material parameter DiffuseMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
Sep 19, 2016 10:49:36 PM com.jme3.material.Material setTextureParam
WARNING: The texture Models/zombiecommon/textures/zombie_common_hood.tga has linear color space, but the material parameter DiffuseMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
Sep 19, 2016 10:49:36 PM com.jme3.material.Material setTextureParam
WARNING: The texture Models/zombiecommon/textures/zombie_common_hood.tga has linear color space, but the material parameter DiffuseMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
Sep 19, 2016 10:49:36 PM com.jme3.texture.Texture read
SEVERE: Cannot locate texture title.png (Flipped) (Mipmapped)
Sep 19, 2016 10:49:36 PM com.jme3.texture.Texture read
SEVERE: Cannot locate texture start1.png (Flipped) (Mipmapped)
Sep 19, 2016 10:49:36 PM com.jme3.texture.Texture read
SEVERE: Cannot locate texture continue1.png (Flipped) (Mipmapped)
[JME3] OpenGL debug message
ID: 1000
Source: API
Type: ERROR
Severity: HIGH
Message: glTexParameteri has generated an error (GL_INVALID_ENUM)
java.lang.Exception: Stack trace
at java.lang.Thread.dumpStack(Thread.java:1329)
at com.jme3.system.lwjgl.LwjglGLDebugOutputHandler.handleMessage(LwjglGLDebugOutputHandler.java:76)
at org.lwjgl.opengl.GL11.nglTexParameteri(Native Method)
at org.lwjgl.opengl.GL11.glTexParameteri(GL11.java:3016)
at com.jme3.renderer.lwjgl.LwjglGL.glTexParameteri(LwjglGL.java:320)
at com.jme3.renderer.opengl.GLDebugES.glTexParameteri(GLDebugES.java:327)
at com.jme3.renderer.opengl.GLRenderer.updateTexImageData(GLRenderer.java:2140)
at com.jme3.renderer.opengl.GLRenderer.updateRenderTexture(GLRenderer.java:1500)
at com.jme3.renderer.opengl.GLRenderer.updateFrameBufferAttachment(GLRenderer.java:1531)
at com.jme3.renderer.opengl.GLRenderer.updateFrameBuffer(GLRenderer.java:1581)
at com.jme3.renderer.opengl.GLRenderer.setFrameBuffer(GLRenderer.java:1736)
at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1072)
at com.jme3.renderer.RenderManager.render(RenderManager.java:1145)
at com.jme3.app.SimpleApplication.update(SimpleApplication.java:253)
at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
at java.lang.Thread.run(Thread.java:745)
Sep 19, 2016 10:49:37 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.renderer.RendererException: An OpenGL error occurred - Invalid enum argument (Error Code: 1280)
at com.jme3.renderer.opengl.GLDebug.checkError(GLDebug.java:46)
at com.jme3.renderer.opengl.GLDebugES.glTexParameteri(GLDebugES.java:328)
at com.jme3.renderer.opengl.GLRenderer.updateTexImageData(GLRenderer.java:2140)
at com.jme3.renderer.opengl.GLRenderer.updateRenderTexture(GLRenderer.java:1500)
at com.jme3.renderer.opengl.GLRenderer.updateFrameBufferAttachment(GLRenderer.java:1531)
at com.jme3.renderer.opengl.GLRenderer.updateFrameBuffer(GLRenderer.java:1581)
at com.jme3.renderer.opengl.GLRenderer.setFrameBuffer(GLRenderer.java:1736)
at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1072)
at com.jme3.renderer.RenderManager.render(RenderManager.java:1145)
at com.jme3.app.SimpleApplication.update(SimpleApplication.java:253)
at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by shadowislord** [comment]
Offending line:
`gl.glTexParameteri(target, GL.GL_TEXTURE_MAX_LEVEL, 0);`

Error:
`Invalid enum argument (Error Code: 1280)`

https://github.com/jMonkeyEngine/jmonkeyengine/blob/v3.1.0-beta1/jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java#L2140

**Comment by Nehon** [comment]
seems it's an opengl only feature
https://www.opengl.org/sdk/docs/man/html/glTexParameter.xhtml

Whereas it's not in opengles
https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameter.xml

Since it's on Desktop and with opengl, it should not be the issue, but I wouldn't be surprised that the drivers are screwed up...

How do we get around this in the android renderer? do we?

**Comment by jojoofu** [comment]
My drivers are up to date and JME 3.0 works on the same computer. Somewhere between 3.0 - 3.1 something got screwed up.

**Comment by Nehon** [comment]
Seems like in 3.0 we were skipping the case where the image has no mipmaps and doesn't not need any, doing nothing.
https://github.com/jMonkeyEngine/jmonkeyengine/blob/3.0/engine/src/lwjgl/com/jme3/renderer/lwjgl/LwjglRenderer.java#L1839
It can explain why it was working before and not anymore even with the same drivers.
But by the specs this means we kept the default value (1000) so maybe the mipmaps were still generated.
Maybe setting GL_TEXTURE_MAX_LEVEL to 0 is the issue, but by the specs, again, it shouldn't.

Specs reference : 
GL_TEXTURE_MAX_LEVEL
Sets the index of the highest defined mipmap level. This is an integer value. The initial value is 1000.

GL_INVALID_VALUE is generated if pname is GL_TEXTURE_BASE_LEVEL or GL_TEXTURE_MAX_LEVEL, and param or params is negative.

(pname is the parameter here it's 0 so it shoudln't be an issue).

**Comment by TehLeo** [comment]
Could you try to add 
gl.glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_BASE_LEVEL, 0);
before the line that throws error and see if it helps?

Other than this, it does not look like you are running opengl es 2.0 which apparently does not support GL_TEXTURE_MAX_LEVEL.

**Comment by jojoofu** [comment]
I'm not sure where the error starts in my application. The stack trace goes right into the lwjgl branch without cluing me in as to where it begun. 

What does that line do ? 

The same downgraded to 3.0 app doesn't cause this error. A change somewhere mess up the compatibility.

**Comment by shadowislord** [comment]
I think I was able to reproduce this issue. It happens when the FPP is configured to use multisampling with `setSamples(X)`. The parameter `GL_TEXTURE_MAX_LEVEL` is illegal for multisampled textures. I am working on a fix atm
