### ISSUE TITLE
ArrayIndexOutOfBoundsException in LinuxDisplay.java

### ISSUE THREAD

**Issue by diederick76** [jMonkeyEngine/jmonkeyengine#665]
Building the BasicGame template project fails with:

```
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.ExceptionInInitializerError
	at com.jme3.system.lwjgl.LwjglDisplay.createContext(LwjglDisplay.java:112)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:113)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 4 more
```

**Comment by diederick76** [comment]
I believe I put this in the wrong project. My apologies.
