### ISSUE TITLE
BinaryExporter/Importer

### ISSUE THREAD

**Issue by TehLeo** [jMonkeyEngine/jmonkeyengine#770]
Information along with test case at: https://hub.jmonkeyengine.org/t/binaryexporter-importer-issues/39655

Copy of the test case:
```
private static void testsave() {
		//no error at loop 1-15 i think
		//ClassCastException at loop = 50
		//ArrayIndexOutOfBoundsException at loop = 40
			
		
//		final int LOOPS = 1;
		final int LOOPS = 40;
//		final int LOOPS = 50;

					
		try {
			Geometry geom = new Geometry("test");
			
			ArrayList<Vector3f[]> faces = new ArrayList<>();
			
			for(int k = 0; k < LOOPS; k++) {
				Vector3f[] face = new Vector3f[]{Vector3f.UNIT_X,Vector3f.UNIT_XYZ, Vector3f.UNIT_Y,Vector3f.UNIT_Z};
				faces.add(face);
				faces.add(new Vector3f[]{});
				faces.add(null);
				faces.add(new Vector3f[]{Vector3f.UNIT_X});
			}
			
			
			geom.setUserData("keepquads", faces);
			
			BinaryExporter exp = BinaryExporter.getInstance();
			exp.save(geom, new File("test.j3o"));
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}
	private static void testload() {
		try {
			BinaryImporter im = BinaryImporter.getInstance();
			Geometry g = (Geometry)im.load( new File("test.j3o"));
			ArrayList<Vector3f[]> faces = g.getUserData("keepquads");
			System.out.println("Load Succeeded Yay");
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}	
	public static void main(String[] args) {
		//feel free to comment one line, to save first then load
		testsave();
		
		testload();
	}
```
Exceptions
```
java.lang.ArrayIndexOutOfBoundsException: -2
	at com.jme3.export.binary.ByteUtils.rightAlignBytes(ByteUtils.java:477)
	at com.jme3.export.binary.BinaryInputCapsule.readInt(BinaryInputCapsule.java:793)
	at com.jme3.export.binary.BinaryInputCapsule.setContent(BinaryInputCapsule.java:154)
....

```
```
java.lang.ClassCastException: java.lang.Float cannot be cast to java.util.ArrayList
	at tests.TestWindow.testload(TestWindow.java:113)
	at tests.TestWindow.main(TestWindow.java:123)
```

**Comment by TehLeo** [comment]
I have tested with jme 3.2 alpha. And it seems this issue has been fixed in that release. Thus, unless someone else can reproduce it I will close this issue.
