### ISSUE TITLE
DetailedProfilerState + assertions enabled = OpenGLException

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#794]
In JME 3.2, I created a new BasicGame project and added
```
stateManager.attach(new DetailedProfilerState());
```
to the simpleInitApp() method. I enabled assertions by putting "-ea" in the runtime VM options.

When executed, the application crashed immediately:
```
Jan 08, 2018 1:47:36 PM com.jme3.app.LegacyApplication handleError
SEVERE: An OpenGL error has occured!
org.lwjgl.opengl.OpenGLException: Invalid operation (1282)
	at org.lwjgl.opengl.Util.checkGLError(Util.java:59)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.checkGLError(LwjglAbstractDisplay.java:136)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:157)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:197)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by stephengold** [comment]
I believe this issue was resolved by d109e47 (in master branch) and 6d2ea28 (in v3.3 branch).
