### ISSUE TITLE
Native Bullet breaks TestFancyCar

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#898]
TestFancyCar works fine with JBullet, but with recent versions of Native Bullet, the test crashes during initialization:
```
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.NullPointerException: The vehicle object does not exist.
	at com.jme3.bullet.PhysicsSpace.addVehicle(Native Method)
	at com.jme3.bullet.PhysicsSpace.addRigidBody(PhysicsSpace.java:639)
	at com.jme3.bullet.PhysicsSpace.addCollisionObject(PhysicsSpace.java:440)
	at com.jme3.bullet.control.VehicleControl.setPhysicsSpace(VehicleControl.java:236)
	at com.jme3.bullet.PhysicsSpace.add(PhysicsSpace.java:419)
	at jme3test.bullet.TestFancyCar.buildPlayer(TestFancyCar.java:211)
	at jme3test.bullet.TestFancyCar.simpleInitApp(TestFancyCar.java:98)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:748)
```

Debugger reveals that the vehicleId is 0 because it was never initialized. createVehicle() was invoked with space=null when the vehicle was instantiated, bypassing most of the initialization code.

**Comment by stephengold** [comment]
Fixed in 'master' branch.
