### ISSUE TITLE
native implementation of TranslationalLimitMotor.getLimitSoftness() has wrong name

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#919]
Spot the typographical error:

```
native private float getLimitSoftness(long motorId);
```
...
```
    JNIEXPORT jfloat JNICALL
    Java_com_jme3_bullet_joints_motors_TranslationalLimitMotor_getLetLimitSoftness(
```

**Comment by stephengold** [comment]
This causes a runtime exception:
```
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.UnsatisfiedLinkError: com.jme3.bullet.joints.motors.TranslationalLimitMotor.getLimitSoftness(J)F
	at com.jme3.bullet.joints.motors.TranslationalLimitMotor.getLimitSoftness(Native Method)
	at com.jme3.bullet.joints.motors.TranslationalLimitMotor.getLimitSoftness(TranslationalLimitMotor.java:154)
```

**Comment by empirephoenix** [comment]
Nothing of value to add, just wanting to say Thank You for taking a deep look at all of the native parts  :1st_place_medal:

**Comment by stephengold** [comment]
Fixed in the `master` branch.
