### ISSUE TITLE
All the tests crashes under Ubuntu-Linux

### ISSUE THREAD

**Issue by neo-expert** [jMonkeyEngine/jmonkeyengine#949]
After running "./gradlew" and starting a test the application crashes with following error:
```
An OpenGL error has occured!
OpenGLException: Invalid enum (1280)
```
in terminal:
```
org.lwjgl.opengl.OpenGLException: Invalid enum (1280)
        at org.lwjgl.opengl.Util.checkGLError(Util.java:59)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.checkGLError(LwjglAbstractDisplay.java:136)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:157)
        at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:197)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by empirephoenix** [comment]
You need to supply more information if you want any actual help. Hardware, Software, does other opengl based java software work?

**Comment by neo-expert** [comment]
I've tested some other openGL projects (OpenTomb and lwjgl3-demos). They do work.
I just ran the test class "jme3test.awt.TestCanvas" - this worked.
Can we determine wich GL-Call actually failed?

**Comment by neo-expert** [comment]
the test class `jme3test.awt.TestAwtPanels`
fails with following error:
```
Failed to create display
LWJGLException: Parent.isDisplayable() must be true
```

Stacktrace:
```
SEVERE LegacyApplication 10:43:36 Failed to create display
org.lwjgl.LWJGLException: Parent.isDisplayable() must be true
        at org.lwjgl.opengl.Display.createWindow(Display.java:301)
        at org.lwjgl.opengl.Display.create(Display.java:848)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at com.jme3.system.lwjgl.LwjglDisplay.createContext(LwjglDisplay.java:143)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:113)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
        at java.lang.Thread.run(Thread.java:748)
SEVERE LwjglAbstractDisplay 10:43:36 Display initialization failed. Cannot continue.

```

**Comment by Ev1lbl0w** [comment]
What graphics card are you using? What driver are you using? Give us more info about your setup.

**Comment by louhy** [comment]
Also on Linux here and I see the same, but I don't believe this is Linux specific at all. 

The problem is that there's crucial code in TestAwtPanels main() which TestChooser doesn't execute, because it doesn't execute main() on regular tests. It's not as simple as moving that code into simpleInitApp(), because part of the code sets a custom graphics renderer (an AwtPanelsContext) on AppSettings prior to calling start(). I think that's the root of the problem. 

Before I spend time on a fix, **is this even worth fixing?** It's somewhat of a niche test (or example?) to begin with, and it works fine running standalone. 

Otherwise, here's 3 potential options: 
1) I tried forcing TestChooser to call the test's main(). This "works" for TestAwtPanels--but only for the first run. The second time, you get a brand new lovely Exception: 

```
SEVERE: Uncaught exception thrown in Thread[jME3 Main,6,main]
java.lang.IllegalStateException: Why did you change the output framebuffer?
	at com.jme3.system.awt.AwtPanel.postFrame(AwtPanel.java:325)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1114)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1166)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:270)
	at com.jme3.system.awt.AwtPanelsContext.updateInThread(AwtPanelsContext.java:200)
	at com.jme3.system.awt.AwtPanelsContext.access$100(AwtPanelsContext.java:45)
	at com.jme3.system.awt.AwtPanelsContext$AwtPanelsListener.update(AwtPanelsContext.java:69)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.runLoop(LwjglOffscreenBuffer.java:125)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.run(LwjglOffscreenBuffer.java:156)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

(I love how the message questions the caller. "WHY did you do this? Are you nuts???") 

Perhaps this can also be prevented, but since it also will require special hacky code inside TestChooser to get it to call the test's main(), it looks like a sucky solution. 

2) Move the special code in main() to a TestAwtPanels constructor. I've also tested this and it works fine, but it suffers from the same "second run" problem in # 1. 

3) Find a way to exclude this test from TestChooser and treat it as a manual-run test only, possibly by moving it to a package that TestChooser ignores. Long term I feel like jme3-examples itself needs organizational updates anyway.
