### ISSUE TITLE
TestModelExportingCloning fails with new Animation system 

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#972]
Running following test fails 

https://github.com/jMonkeyEngine/jmonkeyengine/blob/cde3c39c4f0c131c8d536ef369991de1967ef3c1/jme3-examples/src/main/java/jme3test/model/anim/TestModelExportingCloning.java#L42

with this exception

```
java.lang.IllegalArgumentException: Object is not cloneable, type:class com.jme3.anim.tween.action.ClipAction
	at com.jme3.util.clone.Cloner.clone(Cloner.java:262)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.anim.AnimComposer.cloneFields(AnimComposer.java:191)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:255)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.util.clone.ListCloneFunction.cloneFields(ListCloneFunction.java:66)
	at com.jme3.util.clone.ListCloneFunction.cloneFields(ListCloneFunction.java:43)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:228)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.scene.Spatial.cloneFields(Spatial.java:1446)
	at com.jme3.scene.Node.cloneFields(Node.java:725)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:255)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.scene.Spatial.clone(Spatial.java:1359)
	at com.jme3.scene.Node.clone(Node.java:684)
	at com.jme3.scene.Node.clone(Node.java:61)
	at com.jme3.scene.Spatial.clone(Spatial.java:1389)
	at jme3test.model.anim.TestModelExportingCloning.simpleInitApp(TestModelExportingCloning.java:66)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglWindow.initInThread(LwjglWindow.java:475)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:574)
	at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:423)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:463)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:424)
	at com.jme3.app.SimpleApplication.start(SimpleApplication.java:125)
	at jme3test.model.anim.TestModelExportingCloning.main(TestModelExportingCloning.java:46)
Caused by: java.lang.CloneNotSupportedException: No public clone method found for:class com.jme3.anim.tween.action.ClipAction
	at com.jme3.util.clone.Cloner.javaClone(Cloner.java:366)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:260)
	... 25 more
```

**Comment by stephengold** [comment]
I reproduced the issue. Looks like `Action`, `BlendableAction`, and `ClipAction` all need some cloning methods implemented.
