### ISSUE TITLE
jme3test.audio.TestMusicStreaming crashes due to missing asset

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#983]
The OGG file required to run `TestMusicStreaming` has moved. The URL needs to be updated.

Currently (in `master` branch at 3.3-6680) `TestMusicStreaming` crashes with the following stack trace:
```
Ogg packet header is 0x3c21444f (<!DO), should be 0x4f676753 (OggS)
Dec 29, 2018 9:45:36 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.asset.AssetLoadException: An exception has occured while loading asset: Lumme-Badloop.ogg (Stream/Cache)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:261)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at com.jme3.audio.AudioNode.<init>(AudioNode.java:163)
	at com.jme3.audio.AudioNode.<init>(AudioNode.java:144)
	at jme3test.audio.TestMusicStreaming.simpleInitApp(TestMusicStreaming.java:50)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:748)
Caused by: de.jarnbjo.ogg.EndOfOggStreamException
	at de.jarnbjo.ogg.OggPage.readFully(OggPage.java:302)
	at de.jarnbjo.ogg.OggPage.create(OggPage.java:283)
	at de.jarnbjo.ogg.OggPage.create(OggPage.java:156)
	at de.jarnbjo.ogg.OggPage.create(OggPage.java:134)
	at com.jme3.audio.plugins.CachedOggStream.readOggNextPage(CachedOggStream.java:127)
	at com.jme3.audio.plugins.CachedOggStream.<init>(CachedOggStream.java:73)
	at com.jme3.audio.plugins.OGGLoader.load(OGGLoader.java:264)
	at com.jme3.audio.plugins.OGGLoader.load(OGGLoader.java:309)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	... 8 more


```

**Comment by stephengold** [comment]
fixed in master branch at SHA id=bbf1f73a8912640b9056bd730ed6f1d4128dc95f using the Internet Archive's Wayback Machine
