### ISSUE TITLE
jme3test.blender.TestBlenderLoader throws an OutOfMemoryError

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#984]
Currently (in `master` branch at 3.3-6680) `TestBlenderLoader` crashes with the following stack trace:
```
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.file.FileBlockHeader$BlockCode valueOf
WARNING: Unknown block header: PY00
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.file.FileBlockHeader$BlockCode valueOf
WARNING: Unknown block header: PY00
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.file.FileBlockHeader$BlockCode valueOf
WARNING: Unknown block header: PY00
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Loading animations that will be later applied to scene features.
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Found animation: Dance.
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Found animation: DrawSwords.
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Found animation: HandsClosed.
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Found animation: HandsRelaxed.
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Found animation: IdleBase.
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Found animation: IdleTop.
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Found animation: JumpEnd.
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Found animation: JumpLoop.
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Found animation: JumpStart.
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Found animation: RunBase.
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Found animation: RunTop.
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Found animation: SliceHorizontal.
Dec 29, 2018 10:14:34 AM com.jme3.scene.plugins.blender.animations.AnimationHelper loadAnimations
INFO: Found animation: SliceVertical.
Dec 29, 2018 10:14:35 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.OutOfMemoryError: Java heap space
	at com.jme3.texture.plugins.TGALoader.load(TGALoader.java:205)
	at com.jme3.texture.plugins.TGALoader.load(TGALoader.java:83)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	at com.jme3.asset.DesktopAssetManager.loadAssetFromStream(DesktopAssetManager.java:341)
	at com.jme3.scene.plugins.blender.textures.ImageLoader.loadTexture(ImageLoader.java:118)
	at com.jme3.scene.plugins.blender.textures.TextureHelper.loadImageAsTexture(TextureHelper.java:255)
	at com.jme3.scene.plugins.blender.BlenderLoader.load(BlenderLoader.java:133)
	at com.jme3.scene.plugins.blender.BlenderLoader.load(BlenderLoader.java:88)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:420)
	at jme3test.blender.TestBlenderLoader.simpleInitApp(TestBlenderLoader.java:53)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by stephengold** [comment]
`TGALoader.load()` seems to expect that `pixelDepth` should be either 24 or 32: if it's not 32, it just assumes 24.

In fact, `pixelDepth` is 94, read from `in` back at line 145. The lack of input checking is an issue. Also, the file may be garbled.

**Comment by stephengold** [comment]
The same failure was observed during 3.3.1 testing.

**Comment by ertugrulcetin** [comment]
@stephengold also **3.3.2-stable** has the same problem. I'm using blender plugin: `compile group: 'org.jmonkeyengine', name: 'jme3-blender', version: '3.2.0-beta1'`

**Comment by Ali-RS** [comment]
Blender importer is removed in the master branch and JME 3.4 will not support importing blender files. You should use Gltf instead.

Maybe we should close this issue or tag it with "won't fix"

**Comment by stephengold** [comment]
`TestBlenderLoader` was removed from the "master" branch by PR #1348
