### ISSUE TITLE
HelloCollision throws an AssetLoadException

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#992]
Currently (in master branch at 3.3-6684) TestAssetLinkNode crashes with the following stack trace:
```
Dec 30, 2018 11:08:09 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.asset.AssetLoadException: Failed to open zip file: town.zip
	at com.jme3.asset.plugins.ZipLocator.setRootPath(ZipLocator.java:79)
	at com.jme3.asset.ImplHandler$ImplThreadLocal.initialValue(ImplHandler.java:120)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at com.jme3.asset.ImplHandler.tryLocate(ImplHandler.java:178)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:359)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:420)
	at jme3test.helloworld.HelloCollision.simpleInitApp(HelloCollision.java:92)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: town.zip (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at com.jme3.asset.plugins.ZipLocator.setRootPath(ZipLocator.java:77)
	... 12 more
```

**Comment by stephengold** [comment]
fixed in master branch at SHA id=2a904034c29d11a8f9bb96f0ca4afbd453883612

HelloCollision still doesn't work right with native Bullet, but that's a separate issue #910.
