### ISSUE TITLE
jme3test.model.TestGltfLoading throws AssetNotFoundException

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#993]
Currently (in `master` branch at 3.3-6687) the `TestGltfLoading` app crashes with the following stack trace:
```
Dec 31, 2018 9:01:53 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.asset.AssetNotFoundException: Models/gltf/izzy/scene.gltf
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:370)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
	at jme3test.model.TestGltfLoading.loadModel(TestGltfLoading.java:239)
	at jme3test.model.TestGltfLoading.simpleInitApp(TestGltfLoading.java:127)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:748)
```

The `TestGltfLoading` app also crashes in `v3.2` branch, but for a different reason.

**Comment by stephengold** [comment]
Fixed in `master` branch at hash  b9ea66139106d0f21da1ca7b52b40fcbae98a011 .
