### ISSUE TITLE
wildhouse.zip Not Found

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#994]
Currently (in `master` branch at 3.3-6688) the `TestMultiplesFilters` app crashes with an `IOException` because the `wildhouse.zip` archive is no longer at the old URL. Here is a typical stack trace:
```
Dec 31, 2018 9:35:43 AM com.jme3.asset.plugins.HttpZipLocator setRootPath
WARNING: Failed to set root path http://jmonkeyengine.googlecode.com/files/wildhouse.zip
java.io.IOException: 404 Not Found
	at com.jme3.asset.plugins.HttpZipLocator.readData(HttpZipLocator.java:196)
	at com.jme3.asset.plugins.HttpZipLocator.readEndHeader(HttpZipLocator.java:295)
	at com.jme3.asset.plugins.HttpZipLocator.load(HttpZipLocator.java:322)
	at com.jme3.asset.plugins.HttpZipLocator.setRootPath(HttpZipLocator.java:346)
	at com.jme3.asset.ImplHandler$ImplThreadLocal.initialValue(ImplHandler.java:120)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at com.jme3.asset.ImplHandler.tryLocate(ImplHandler.java:178)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:359)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:420)
	at jme3test.post.TestMultiplesFilters.simpleInitApp(TestMultiplesFilters.java:86)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:748)

Dec 31, 2018 9:35:43 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.NullPointerException
	at com.jme3.asset.plugins.HttpZipLocator.locate(HttpZipLocator.java:354)
	at com.jme3.asset.ImplHandler.tryLocate(ImplHandler.java:178)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:359)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:420)
	at jme3test.post.TestMultiplesFilters.simpleInitApp(TestMultiplesFilters.java:86)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:748)

```

The new location is: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/jmonkeyengine/wildhouse.zip

**Comment by stephengold** [comment]
This issue also impacts the `TestManyLocators` and `TestPostWaterLake` example apps.

**Comment by stephengold** [comment]
Fixed in `master` branch. See also issue #982.
