### ISSUE TITLE
jme3test.terrain.TerrainGridAlphaMapTest throws AssetLoadException

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#996]
Currently (in `master` branch at 3.3-6689) the `TerrainGridAlphaMapTest` app crashes with the following stack trace:
```
Dec 31, 2018 10:28:11 AM com.jme3.terrain.noise.filter.PerturbFilter filter
INFO: Found origSize : 147 and offset: 17 for workSize : 181 and magnitude : 0.119
Dec 31, 2018 10:28:11 AM com.jme3.terrain.noise.filter.PerturbFilter filter
INFO: Found origSize : 147 and offset: 17 for workSize : 181 and magnitude : 0.119
Dec 31, 2018 10:28:12 AM class com.jme3.app.AppTask invoke()
SEVERE: Exception
com.jme3.asset.AssetLoadException: The given image cannot be loaded TerrainAlphaTest/alpha_default.png (Flipped) (Mipmapped)
	at com.jme3.texture.plugins.AWTLoader.load(AWTLoader.java:194)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:390)
	at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:400)
	at jme3test.terrain.TerrainGridAlphaMapTest$2.tileAttached(TerrainGridAlphaMapTest.java:193)
	at com.jme3.terrain.geomipmap.TerrainGrid.attachQuadAt(TerrainGrid.java:368)
	at com.jme3.terrain.geomipmap.TerrainGrid$UpdateQuadCache$1.call(TerrainGrid.java:173)
	at com.jme3.app.AppTask.invoke(AppTask.java:142)
	at com.jme3.scene.control.UpdateControl.controlUpdate(UpdateControl.java:78)
	at com.jme3.scene.control.AbstractControl.update(AbstractControl.java:111)
	at com.jme3.scene.Spatial.runControlUpdate(Spatial.java:737)
	at com.jme3.scene.Spatial.updateLogicalState(Spatial.java:880)
	at com.jme3.scene.Node.updateLogicalState(Node.java:232)
	at com.jme3.scene.Node.updateLogicalState(Node.java:243)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:242)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:197)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:748)

Dec 31, 2018 10:28:13 AM class com.jme3.app.AppTask invoke()
SEVERE: Exception
com.jme3.asset.AssetLoadException: The given image cannot be loaded TerrainAlphaTest/alpha_default.png (Flipped) (Mipmapped)
	at com.jme3.texture.plugins.AWTLoader.load(AWTLoader.java:194)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:390)
	at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:400)
	at jme3test.terrain.TerrainGridAlphaMapTest$2.tileAttached(TerrainGridAlphaMapTest.java:193)
	at com.jme3.terrain.geomipmap.TerrainGrid.attachQuadAt(TerrainGrid.java:368)
	at com.jme3.terrain.geomipmap.TerrainGrid$UpdateQuadCache$1.call(TerrainGrid.java:173)
	at com.jme3.app.AppTask.invoke(AppTask.java:142)
	at com.jme3.scene.control.UpdateControl.controlUpdate(UpdateControl.java:78)
	at com.jme3.scene.control.AbstractControl.update(AbstractControl.java:111)
	at com.jme3.scene.Spatial.runControlUpdate(Spatial.java:737)
	at com.jme3.scene.Spatial.updateLogicalState(Spatial.java:880)
	at com.jme3.scene.Node.updateLogicalState(Node.java:232)
	at com.jme3.scene.Node.updateLogicalState(Node.java:243)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:242)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:197)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:748)

Dec 31, 2018 10:28:13 AM class com.jme3.app.AppTask invoke()
SEVERE: Exception
com.jme3.asset.AssetLoadException: The given image cannot be loaded TerrainAlphaTest/alpha_default.png (Flipped) (Mipmapped)
	at com.jme3.texture.plugins.AWTLoader.load(AWTLoader.java:194)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:390)
	at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:400)
	at jme3test.terrain.TerrainGridAlphaMapTest$2.tileAttached(TerrainGridAlphaMapTest.java:193)
	at com.jme3.terrain.geomipmap.TerrainGrid.attachQuadAt(TerrainGrid.java:368)
	at com.jme3.terrain.geomipmap.TerrainGrid$UpdateQuadCache$1.call(TerrainGrid.java:173)
	at com.jme3.app.AppTask.invoke(AppTask.java:142)
	at com.jme3.scene.control.UpdateControl.controlUpdate(UpdateControl.java:78)
	at com.jme3.scene.control.AbstractControl.update(AbstractControl.java:111)
	at com.jme3.scene.Spatial.runControlUpdate(Spatial.java:737)
	at com.jme3.scene.Spatial.updateLogicalState(Spatial.java:880)
	at com.jme3.scene.Node.updateLogicalState(Node.java:232)
	at com.jme3.scene.Node.updateLogicalState(Node.java:243)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:242)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:197)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:748)

Dec 31, 2018 10:28:13 AM class com.jme3.app.AppTask invoke()
SEVERE: Exception
com.jme3.asset.AssetLoadException: The given image cannot be loaded TerrainAlphaTest/alpha_default.png (Flipped) (Mipmapped)
	at com.jme3.texture.plugins.AWTLoader.load(AWTLoader.java:194)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:390)
	at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:400)
	at jme3test.terrain.TerrainGridAlphaMapTest$2.tileAttached(TerrainGridAlphaMapTest.java:193)
	at com.jme3.terrain.geomipmap.TerrainGrid.attachQuadAt(TerrainGrid.java:368)
	at com.jme3.terrain.geomipmap.TerrainGrid$UpdateQuadCache$1.call(TerrainGrid.java:173)
	at com.jme3.app.AppTask.invoke(AppTask.java:142)
	at com.jme3.scene.control.UpdateControl.controlUpdate(UpdateControl.java:78)
	at com.jme3.scene.control.AbstractControl.update(AbstractControl.java:111)
	at com.jme3.scene.Spatial.runControlUpdate(Spatial.java:737)
	at com.jme3.scene.Spatial.updateLogicalState(Spatial.java:880)
	at com.jme3.scene.Node.updateLogicalState(Node.java:232)
	at com.jme3.scene.Node.updateLogicalState(Node.java:243)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:242)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:197)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:748)

fixed normals (0.0, 0.0, 0.0)
```

**Comment by stephengold** [comment]
Fixed in `master` branch at SHA hash 7c6d828.
