### ISSUE TITLE
TerrainGridTest throws AssetLoadException

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#998]
Currently (in `master` branch at 3.3-6689) the `jme3test.terrain.TerrainGridTest` app generates the following stack trace:
```
Dec 31, 2018 10:39:51 AM com.jme3.material.plugins.J3MLoader readTechnique
WARNING: Fixed function technique was ignored
Dec 31, 2018 10:39:51 AM com.jme3.material.plugins.J3MLoader readTechnique
WARNING: Fixed function technique 'Default' was ignored for material Common/MatDefs/Terrain/HeightBasedTerrain.j3md
com.jme3.asset.AssetLoadException: The given image cannot be loaded Scenes/TerrainMountains/terrain_-1_-1.png (Flipped)
	at com.jme3.texture.plugins.AWTLoader.load(AWTLoader.java:194)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:390)
	at com.jme3.terrain.geomipmap.grid.ImageTileLoader.getHeightMapAt(ImageTileLoader.java:117)
	at com.jme3.terrain.geomipmap.grid.ImageTileLoader.getTerrainQuadAt(ImageTileLoader.java:160)
	at com.jme3.terrain.geomipmap.TerrainGrid$UpdateQuadCache.run(TerrainGrid.java:152)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by stephengold** [comment]
Nope. That just leads me back to the URL that's currently used in `master`. Perhaps the contents of `TerrainGridTestData.zip` have changed since it was archived.

**Comment by stephengold** [comment]
Fixed in `master`. I recovered `TerrainGridTestData.zip` via the Internet Archive's Wayback Machine.

**Comment by stephengold** [comment]
The issue came up again at the Forum:
 https://hub.jmonkeyengine.org/t/terraingridtestdata-zip-download/41480
